-- Current data backup before restore
SET FOREIGN_KEY_CHECKS = 0;

-- categories
INSERT INTO categories (id, name, description, parent_id, level, image_url, localized_content) VALUES (1, 'Pet Supplies', 'English default catalog root for pet-only test data.', NULL, 1, 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=900&q=80', NULL);
INSERT INTO categories (id, name, description, parent_id, level, image_url, localized_content) VALUES (2, 'Pet Food', 'Dry food, wet food, treats and supplements for dogs and cats.', 1, 2, 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=900&q=80', NULL);
INSERT INTO categories (id, name, description, parent_id, level, image_url, localized_content) VALUES (3, 'Bowls, Feeders & Waterers', 'Automatic feeders, slow feeders, bowls and fountains.', 1, 2, 'https://images.unsplash.com/photo-1601758123927-1967a0d5f11b?auto=format&fit=crop&w=900&q=80', NULL);
INSERT INTO categories (id, name, description, parent_id, level, image_url, localized_content) VALUES (4, 'Beds & Furniture', 'Comfort beds, crates, mats and calming furniture.', 1, 2, 'https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?auto=format&fit=crop&w=900&q=80', NULL);
INSERT INTO categories (id, name, description, parent_id, level, image_url, localized_content) VALUES (5, 'Toys & Enrichment', 'Chew toys, puzzles, teaser toys and training rewards.', 1, 2, 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=80', NULL);
INSERT INTO categories (id, name, description, parent_id, level, image_url, localized_content) VALUES (6, 'Grooming & Hygiene', 'Shampoo, brushes, litter, pads and daily care.', 1, 2, 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=900&q=80', NULL);
INSERT INTO categories (id, name, description, parent_id, level, image_url, localized_content) VALUES (7, 'Walking & Travel', 'Leashes, harnesses, carriers and travel accessories.', 1, 2, 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=900&q=80', NULL);
INSERT INTO categories (id, name, description, parent_id, level, image_url, localized_content) VALUES (8, 'Dog Food', 'Daily nutrition and treats for dogs.', 2, 3, 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=900&q=80', NULL);
INSERT INTO categories (id, name, description, parent_id, level, image_url, localized_content) VALUES (9, 'Cat Food', 'Daily nutrition and treats for cats.', 2, 3, 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=900&q=80', NULL);
INSERT INTO categories (id, name, description, parent_id, level, image_url, localized_content) VALUES (10, 'Automatic Feeders', 'Programmable feeding and portion control.', 3, 3, 'https://images.unsplash.com/photo-1595433707802-6b2626ef1c91?auto=format&fit=crop&w=900&q=80', NULL);
INSERT INTO categories (id, name, description, parent_id, level, image_url, localized_content) VALUES (11, 'Water Fountains', 'Filtered drinking fountains and replacement filters.', 3, 3, 'https://images.unsplash.com/photo-1533743983669-94fa5c4338ec?auto=format&fit=crop&w=900&q=80', NULL);
INSERT INTO categories (id, name, description, parent_id, level, image_url, localized_content) VALUES (12, 'Interactive Toys', 'Puzzle toys and active play for pets.', 5, 3, 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=900&q=80', NULL);
INSERT INTO categories (id, name, description, parent_id, level, image_url, localized_content) VALUES (13, 'Harnesses & Leashes', 'Adjustable walking sets and safety gear.', 7, 3, 'https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?auto=format&fit=crop&w=900&q=80', NULL);

-- products
INSERT INTO products (id, category_id, created_at, description, image_url, is_featured, name, price, stock, updated_at, brand, discount, images, original_price, shipping, specifications, tag, warranty, limited_time_price, limited_time_start_at, limited_time_end_at, status, detail_content, free_shipping, free_shipping_threshold, variants) VALUES (1, 10, NULL, 'Programmable automatic feeder with portion control, sealed food storage and a clear schedule for cats and small dogs.', 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=900&q=80', true, 'PawPilot Smart Pet Feeder 4L', 129.90, 33, '2026-05-12T03:23:50.274755', 'PawPilot', 19, '["https://images.unsplash.com/photo-1601758123927-1967a0d5f11b?auto=format&fit=crop&w=900&q=80","https://images.unsplash.com/photo-1595433707802-6b2626ef1c91?auto=format&fit=crop&w=900&q=80"]', 159.90, 'Ships in a protective box; free over threshold.', '{"Pet Size":"Small, Medium","Capacity":"4 L","Material":"BPA-free ABS","Color":"White","options.Size":"Small,Medium","options.Color":"White,Black","i18n.es.name":"Comedero inteligente PawPilot 4L","i18n.es.description":"Comedero automatico programable con control de porciones para gatos y perros pequenos.","i18n.zh.name":"PawPilot 4L \\u667a\\u80fd\\u5ba0\\u7269\\u5582\\u98df\\u5668","i18n.zh.description":"\\u652f\\u6301\\u5b9a\\u65f6\\u4e0e\\u5206\\u91cf\\u63a7\\u5236\\u7684\\u81ea\\u52a8\\u5582\\u98df\\u5668\\uff0c\\u9002\\u5408\\u732b\\u548c\\u5c0f\\u578b\\u72ac\\u3002"}', 'hot', '1 year limited warranty', 109.90, '2026-05-01T00:00', '2026-06-30T23:59:59', 'ACTIVE', '[{"type":"text","content":"Set up to six meals per day and keep dry food fresh with the sealed hopper."},{"type":"text","content":"English is the default content. Spanish and Chinese demo text is stored in specifications for language fallback testing."}]', true, 899.00, NULL);
INSERT INTO products (id, category_id, created_at, description, image_url, is_featured, name, price, stock, updated_at, brand, discount, images, original_price, shipping, specifications, tag, warranty, limited_time_price, limited_time_start_at, limited_time_end_at, status, detail_content, free_shipping, free_shipping_threshold, variants) VALUES (2, 11, NULL, 'Low-noise filtered water fountain that encourages cats to drink more throughout the day.', 'https://images.unsplash.com/photo-1533743983669-94fa5c4338ec?auto=format&fit=crop&w=900&q=80', true, 'HydraWhisk Quiet Cat Water Fountain', 49.90, 75, NULL, 'HydraWhisk', 23, '["https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=900&q=80"]', 64.90, 'Standard shipping', '{"Pet Size":"Cat","Capacity":"2.5 L","Material":"Stainless steel, ABS","Color":"Blue","options.Color":"Blue,White","Filter":"Replace every 30 days","i18n.es.name":"Fuente silenciosa HydraWhisk para gato","i18n.es.description":"Fuente filtrada de bajo ruido que ayuda a los gatos a beber mas agua."}', 'new', '6 month warranty', NULL, NULL, NULL, 'ACTIVE', '[{"type":"text","content":"Circulating water and replaceable filters help keep every sip fresh."}]', false, NULL, NULL);
INSERT INTO products (id, category_id, created_at, description, image_url, is_featured, name, price, stock, updated_at, brand, discount, images, original_price, shipping, specifications, tag, warranty, limited_time_price, limited_time_start_at, limited_time_end_at, status, detail_content, free_shipping, free_shipping_threshold, variants) VALUES (3, 13, NULL, 'Leash, collar and waste-bag holder bundled for safer daily walks at one special set price.', 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=900&q=80', false, 'TrailTails Walking Starter Bundle', 34.90, 120, NULL, 'TrailTails', 27, '["https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?auto=format&fit=crop&w=900&q=80"]', 54.90, 'Standard shipping', '{"Pet Size":"Small, Medium, Large","Material":"Nylon","Color":"Black","options.Size":"Small,Medium,Large","options.Color":"Black,Red,Blue","Closure":"Quick-release buckles","bundle.enabled":"true","bundle.title":"Leash + Collar + Waste Bags","bundle.price":"39.90","bundle.items":"[{"name":"Adjustable leash","quantity":1},{"name":"Matching collar","quantity":1},{"name":"Waste-bag roll","quantity":2}]"}', 'hot', '1 year limited warranty', NULL, NULL, NULL, 'ACTIVE', '[{"type":"text","content":"Adjustable neck and chest straps help the harness fit growing pets and different breeds."},{"type":"text","content":"Bundle includes a matching walking set for first-time pet parents."}]', false, NULL, NULL);
INSERT INTO products (id, category_id, created_at, description, image_url, is_featured, name, price, stock, updated_at, brand, discount, images, original_price, shipping, specifications, tag, warranty, limited_time_price, limited_time_start_at, limited_time_end_at, status, detail_content, free_shipping, free_shipping_threshold, variants) VALUES (4, 4, NULL, 'Bolstered pet bed with orthopedic foam support and a washable cover for deep everyday rest.', 'https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?auto=format&fit=crop&w=900&q=80', true, 'CloudNap Orthopedic Calming Bed', 89.90, 36, NULL, 'CloudNap', 18, '["https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=80"]', 109.90, 'Ships compressed; allow 24 hours to expand.', '{"Pet Size":"Medium, Large","Material":"Orthopedic foam, plush cover","Color":"Gray","options.Size":"Medium,Large","options.Color":"Gray,Brown","Care":"Machine-washable cover"}', 'discount', '1 year limited warranty', 79.90, '2026-05-01T00:00', '2026-05-31T23:59:59', 'ACTIVE', '[{"type":"text","content":"The raised edge supports curled sleepers while the foam base cushions joints."}]', true, 899.00, NULL);
INSERT INTO products (id, category_id, created_at, description, image_url, is_featured, name, price, stock, updated_at, brand, discount, images, original_price, shipping, specifications, tag, warranty, limited_time_price, limited_time_start_at, limited_time_end_at, status, detail_content, free_shipping, free_shipping_threshold, variants) VALUES (5, 12, NULL, 'Durable chew toy pair with textured ridges for enrichment and everyday dental care.', 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=900&q=80', false, 'BrightBite Dental Chew Toy Set', 18.90, 180, NULL, 'BrightBite', 24, '["https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=80"]', 24.90, 'Standard shipping', '{"Pet Size":"Small, Medium","Material":"Silicone","Color":"Green","options.Size":"Small,Medium","options.Color":"Green,Orange","Pack":"2 pieces"}', 'new', '30 day replacement for manufacturing defects', NULL, NULL, NULL, 'ACTIVE', '[{"type":"text","content":"Textured surfaces help massage gums during supervised play."}]', false, NULL, NULL);
INSERT INTO products (id, category_id, created_at, description, image_url, is_featured, name, price, stock, updated_at, brand, discount, images, original_price, shipping, specifications, tag, warranty, limited_time_price, limited_time_start_at, limited_time_end_at, status, detail_content, free_shipping, free_shipping_threshold, variants) VALUES (6, 6, NULL, 'Gentle oatmeal shampoo for sensitive skin, designed for dogs and cats with a light clean scent.', 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=900&q=80', false, 'PurePaws Oatmeal Sensitive Shampoo', 15.90, 95, NULL, 'PurePaws', 20, '["https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=900&q=80"]', 19.90, 'Standard shipping', '{"Pet Size":"All sizes","Volume":"500 ml","Formula":"Oatmeal, aloe","Coat Type":"Sensitive skin"}', NULL, 'Quality guarantee', NULL, NULL, NULL, 'ACTIVE', '[{"type":"text","content":"A mild grooming essential for routine baths and coat care."}]', false, NULL, NULL);
INSERT INTO products (id, category_id, created_at, description, image_url, is_featured, name, price, stock, updated_at, brand, discount, images, original_price, shipping, specifications, tag, warranty, limited_time_price, limited_time_start_at, limited_time_end_at, status, detail_content, free_shipping, free_shipping_threshold, variants) VALUES (7, 9, NULL, 'Complete dry cat food with salmon protein, taurine and balanced minerals for adult cats.', 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=900&q=80', true, 'NutriTail Grain-Free Salmon Cat Food 2kg', 32.90, 88, NULL, 'NutriTail', 18, '["https://images.unsplash.com/photo-1595433707802-6b2626ef1c91?auto=format&fit=crop&w=900&q=80"]', 39.90, 'Food items ship separately when needed.', '{"Pet Size":"Cat","Weight":"2 kg","Flavor":"Salmon","Life Stage":"Adult"}', 'hot', 'Freshness guarantee', NULL, NULL, NULL, 'ACTIVE', '[{"type":"text","content":"Balanced daily nutrition for adult cats with a fish-first flavor profile."}]', false, NULL, NULL);
INSERT INTO products (id, category_id, created_at, description, image_url, is_featured, name, price, stock, updated_at, brand, discount, images, original_price, shipping, specifications, tag, warranty, limited_time_price, limited_time_start_at, limited_time_end_at, status, detail_content, free_shipping, free_shipping_threshold, variants) VALUES (8, 8, NULL, 'Soft bite-size chicken treats for puppy training, recall practice and positive reinforcement.', 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=900&q=80', false, 'CanineCore Puppy Training Treats', 12.90, 160, NULL, 'CanineCore', 24, '["https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=900&q=80"]', 16.90, 'Standard shipping', '{"Pet Size":"Small, Medium","Weight":"300 g","Flavor":"Chicken","Texture":"Soft"}', 'new', 'Freshness guarantee', NULL, NULL, NULL, 'ACTIVE', '[{"type":"text","content":"Small, soft rewards help keep training fast and focused."}]', false, NULL, NULL);

-- product_questions

-- reviews

-- wishlist

-- cart_items

-- order_items
INSERT INTO order_items (id, order_id, product_id, quantity, price, created_at, product_name_snapshot, image_url_snapshot, selected_specs) VALUES (18, 16, 2, 1, 49.90, '2026-05-10 18:22:18', 'HydraWhisk Quiet Cat Water Fountain', 'https://images.unsplash.com/photo-1533743983669-94fa5c4338ec?auto=format&fit=crop&w=900&q=80', '{"Color":"White"}');
INSERT INTO order_items (id, order_id, product_id, quantity, price, created_at, product_name_snapshot, image_url_snapshot, selected_specs) VALUES (19, 17, 1, 1, 109.90, '2026-05-10 18:54:34', 'PawPilot Smart Pet Feeder 4L', 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=900&q=80', '{"Size":"Medium","Color":"Black"}');
INSERT INTO order_items (id, order_id, product_id, quantity, price, created_at, product_name_snapshot, image_url_snapshot, selected_specs) VALUES (20, 18, 8, 1, 12.90, '2026-05-10 18:54:59', 'CanineCore Puppy Training Treats', 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=900&q=80', NULL);
INSERT INTO order_items (id, order_id, product_id, quantity, price, created_at, product_name_snapshot, image_url_snapshot, selected_specs) VALUES (21, 19, 8, 1, 12.90, '2026-05-10 19:19:17', 'CanineCore Puppy Training Treats', 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=900&q=80', NULL);
INSERT INTO order_items (id, order_id, product_id, quantity, price, created_at, product_name_snapshot, image_url_snapshot, selected_specs) VALUES (22, 20, 3, 1, 27.92, '2026-05-11 16:36:35', 'TrailTails Walking Starter Bundle', 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=900&q=80', '{"_purchaseMode":"subscribe","_subscriptionInterval":"8w","_subscriptionDiscountPercent":"20"}');
INSERT INTO order_items (id, order_id, product_id, quantity, price, created_at, product_name_snapshot, image_url_snapshot, selected_specs) VALUES (23, 21, 1, 1, 109.90, '2026-05-11 17:00:15', 'PawPilot Smart Pet Feeder 4L', 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=900&q=80', '{"Size":"Medium","Color":"Black"}');
INSERT INTO order_items (id, order_id, product_id, quantity, price, created_at, product_name_snapshot, image_url_snapshot, selected_specs) VALUES (24, 22, 2, 1, 49.90, '2026-05-11 17:10:19', 'HydraWhisk Quiet Cat Water Fountain', 'https://images.unsplash.com/photo-1533743983669-94fa5c4338ec?auto=format&fit=crop&w=900&q=80', '{"Color":"White"}');
INSERT INTO order_items (id, order_id, product_id, quantity, price, created_at, product_name_snapshot, image_url_snapshot, selected_specs) VALUES (25, 23, 1, 9, 109.90, '2026-05-11 17:23:50', 'PawPilot Smart Pet Feeder 4L', 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=900&q=80', '{"Size":"Small","Color":"White"}');

SET FOREIGN_KEY_CHECKS = 1;
