-- Product/category backup before pet catalog reset
-- Restore order: categories first, then products
SET FOREIGN_KEY_CHECKS = 0;

-- categories
INSERT INTO categories (id, name, description, parent_id, level, image_url) VALUES (1, 'Pet Supplies', 'English default catalog root for pet-only test data.', NULL, 1, 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=900&q=80');
INSERT INTO categories (id, name, description, parent_id, level, image_url) VALUES (2, 'Pet Food', 'Dry food, wet food, treats and supplements for dogs and cats.', 1, 2, 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=900&q=80');
INSERT INTO categories (id, name, description, parent_id, level, image_url) VALUES (3, 'Bowls, Feeders & Waterers', 'Automatic feeders, slow feeders, bowls and fountains.', 1, 2, 'https://images.unsplash.com/photo-1601758123927-1967a0d5f11b?auto=format&fit=crop&w=900&q=80');
INSERT INTO categories (id, name, description, parent_id, level, image_url) VALUES (4, 'Beds & Furniture', 'Comfort beds, crates, mats and calming furniture.', 1, 2, 'https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?auto=format&fit=crop&w=900&q=80');
INSERT INTO categories (id, name, description, parent_id, level, image_url) VALUES (5, 'Toys & Enrichment', 'Chew toys, puzzles, teaser toys and training rewards.', 1, 2, 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=80');
INSERT INTO categories (id, name, description, parent_id, level, image_url) VALUES (6, 'Grooming & Hygiene', 'Shampoo, brushes, litter, pads and daily care.', 1, 2, 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=900&q=80');
INSERT INTO categories (id, name, description, parent_id, level, image_url) VALUES (7, 'Walking & Travel', 'Leashes, harnesses, carriers and travel accessories.', 1, 2, 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=900&q=80');
INSERT INTO categories (id, name, description, parent_id, level, image_url) VALUES (8, 'Dog Food', 'Daily nutrition and treats for dogs.', 2, 3, 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=900&q=80');
INSERT INTO categories (id, name, description, parent_id, level, image_url) VALUES (9, 'Cat Food', 'Daily nutrition and treats for cats.', 2, 3, 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=900&q=80');
INSERT INTO categories (id, name, description, parent_id, level, image_url) VALUES (10, 'Automatic Feeders', 'Programmable feeding and portion control.', 3, 3, 'https://images.unsplash.com/photo-1595433707802-6b2626ef1c91?auto=format&fit=crop&w=900&q=80');
INSERT INTO categories (id, name, description, parent_id, level, image_url) VALUES (11, 'Water Fountains', 'Filtered drinking fountains and replacement filters.', 3, 3, 'https://images.unsplash.com/photo-1533743983669-94fa5c4338ec?auto=format&fit=crop&w=900&q=80');
INSERT INTO categories (id, name, description, parent_id, level, image_url) VALUES (12, 'Interactive Toys', 'Puzzle toys and active play for pets.', 5, 3, 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=900&q=80');
INSERT INTO categories (id, name, description, parent_id, level, image_url) VALUES (13, 'Harnesses & Leashes', 'Adjustable walking sets and safety gear.', 7, 3, 'https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?auto=format&fit=crop&w=900&q=80');

-- products
INSERT INTO products (id, category_id, created_at, description, image_url, is_featured, name, price, stock, updated_at, brand, discount, images, original_price, shipping, specifications, tag, warranty, limited_time_price, limited_time_start_at, limited_time_end_at, status, detail_content, free_shipping, free_shipping_threshold) VALUES (1, 10, NULL, 'Programmable automatic feeder with portion control, sealed food storage and a clear schedule for cats and small dogs.', 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=900&q=80', true, 'PawPilot Smart Pet Feeder 4L', 129.90, 42, NULL, 'PawPilot', 19, '["https://images.unsplash.com/photo-1601758123927-1967a0d5f11b?auto=format&fit=crop&w=900&q=80","https://images.unsplash.com/photo-1595433707802-6b2626ef1c91?auto=format&fit=crop&w=900&q=80"]', 159.90, 'Ships in a protective box; free over threshold.', '{"Pet Size":"Small, Medium","Capacity":"4 L","Material":"BPA-free ABS","Color":"White","i18n.es.name":"Comedero inteligente PawPilot 4L","i18n.es.description":"Comedero automatico programable con control de porciones para gatos y perros pequenos.","i18n.zh.name":"PawPilot 4L 智能宠物喂食器","i18n.zh.description":"支持定时与分量控制的自动喂食器，适合猫和小型犬。"}', 'hot', '1 year limited warranty', 109.90, '2026-05-01T00:00', '2026-06-30T23:59:59', 'ACTIVE', '[{"type":"text","content":"Set up to six meals per day and keep dry food fresh with the sealed hopper."},{"type":"text","content":"English is the default content. Spanish and Chinese demo text is stored in specifications for language fallback testing."}]', true, 899.00);
INSERT INTO products (id, category_id, created_at, description, image_url, is_featured, name, price, stock, updated_at, brand, discount, images, original_price, shipping, specifications, tag, warranty, limited_time_price, limited_time_start_at, limited_time_end_at, status, detail_content, free_shipping, free_shipping_threshold) VALUES (2, 11, NULL, 'Low-noise filtered water fountain that encourages cats to drink more throughout the day.', 'https://images.unsplash.com/photo-1533743983669-94fa5c4338ec?auto=format&fit=crop&w=900&q=80', true, 'HydraWhisk Quiet Cat Water Fountain', 49.90, 75, NULL, 'HydraWhisk', 23, '["https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=900&q=80"]', 64.90, 'Standard shipping', '{"Pet Size":"Cat","Capacity":"2.5 L","Material":"Stainless steel, ABS","Color":"Blue","Filter":"Replace every 30 days","i18n.es.name":"Fuente silenciosa HydraWhisk para gato","i18n.es.description":"Fuente filtrada de bajo ruido que ayuda a los gatos a beber mas agua."}', 'new', '6 month warranty', NULL, NULL, NULL, 'ACTIVE', '[{"type":"text","content":"Circulating water and replaceable filters help keep every sip fresh."}]', false, NULL);
INSERT INTO products (id, category_id, created_at, description, image_url, is_featured, name, price, stock, updated_at, brand, discount, images, original_price, shipping, specifications, tag, warranty, limited_time_price, limited_time_start_at, limited_time_end_at, status, detail_content, free_shipping, free_shipping_threshold) VALUES (3, 13, NULL, 'Soft padded harness with reflective trim and two leash attachment points for safer daily walks.', 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=900&q=80', false, 'TrailTails Adjustable No-Pull Harness', 34.90, 120, NULL, 'TrailTails', 22, '["https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?auto=format&fit=crop&w=900&q=80"]', 44.90, 'Standard shipping', '{"Pet Size":"Small, Medium, Large","Material":"Nylon","Color":"Black","Closure":"Quick-release buckles"}', 'hot', '1 year limited warranty', NULL, NULL, NULL, 'ACTIVE', '[{"type":"text","content":"Adjustable neck and chest straps help the harness fit growing pets and different breeds."}]', false, NULL);
INSERT INTO products (id, category_id, created_at, description, image_url, is_featured, name, price, stock, updated_at, brand, discount, images, original_price, shipping, specifications, tag, warranty, limited_time_price, limited_time_start_at, limited_time_end_at, status, detail_content, free_shipping, free_shipping_threshold) VALUES (4, 4, NULL, 'Bolstered pet bed with orthopedic foam support and a washable cover for deep everyday rest.', 'https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?auto=format&fit=crop&w=900&q=80', true, 'CloudNap Orthopedic Calming Bed', 89.90, 36, NULL, 'CloudNap', 18, '["https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=80"]', 109.90, 'Ships compressed; allow 24 hours to expand.', '{"Pet Size":"Medium, Large","Material":"Orthopedic foam, plush cover","Color":"Gray","Care":"Machine-washable cover"}', 'discount', '1 year limited warranty', 79.90, '2026-05-01T00:00', '2026-05-31T23:59:59', 'ACTIVE', '[{"type":"text","content":"The raised edge supports curled sleepers while the foam base cushions joints."}]', true, 899.00);
INSERT INTO products (id, category_id, created_at, description, image_url, is_featured, name, price, stock, updated_at, brand, discount, images, original_price, shipping, specifications, tag, warranty, limited_time_price, limited_time_start_at, limited_time_end_at, status, detail_content, free_shipping, free_shipping_threshold) VALUES (5, 12, NULL, 'Durable chew toy pair with textured ridges for enrichment and everyday dental care.', 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=900&q=80', false, 'BrightBite Dental Chew Toy Set', 18.90, 180, NULL, 'BrightBite', 24, '["https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=80"]', 24.90, 'Standard shipping', '{"Pet Size":"Small, Medium","Material":"Silicone","Color":"Green","Pack":"2 pieces"}', 'new', '30 day replacement for manufacturing defects', NULL, NULL, NULL, 'ACTIVE', '[{"type":"text","content":"Textured surfaces help massage gums during supervised play."}]', false, NULL);
INSERT INTO products (id, category_id, created_at, description, image_url, is_featured, name, price, stock, updated_at, brand, discount, images, original_price, shipping, specifications, tag, warranty, limited_time_price, limited_time_start_at, limited_time_end_at, status, detail_content, free_shipping, free_shipping_threshold) VALUES (6, 6, NULL, 'Gentle oatmeal shampoo for sensitive skin, designed for dogs and cats with a light clean scent.', 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=900&q=80', false, 'PurePaws Oatmeal Sensitive Shampoo', 15.90, 95, NULL, 'PurePaws', 20, '["https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=900&q=80"]', 19.90, 'Standard shipping', '{"Pet Size":"All sizes","Volume":"500 ml","Formula":"Oatmeal, aloe","Coat Type":"Sensitive skin"}', NULL, 'Quality guarantee', NULL, NULL, NULL, 'ACTIVE', '[{"type":"text","content":"A mild grooming essential for routine baths and coat care."}]', false, NULL);
INSERT INTO products (id, category_id, created_at, description, image_url, is_featured, name, price, stock, updated_at, brand, discount, images, original_price, shipping, specifications, tag, warranty, limited_time_price, limited_time_start_at, limited_time_end_at, status, detail_content, free_shipping, free_shipping_threshold) VALUES (7, 9, NULL, 'Complete dry cat food with salmon protein, taurine and balanced minerals for adult cats.', 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=900&q=80', true, 'NutriTail Grain-Free Salmon Cat Food 2kg', 32.90, 88, NULL, 'NutriTail', 18, '["https://images.unsplash.com/photo-1595433707802-6b2626ef1c91?auto=format&fit=crop&w=900&q=80"]', 39.90, 'Food items ship separately when needed.', '{"Pet Size":"Cat","Weight":"2 kg","Flavor":"Salmon","Life Stage":"Adult"}', 'hot', 'Freshness guarantee', NULL, NULL, NULL, 'ACTIVE', '[{"type":"text","content":"Balanced daily nutrition for adult cats with a fish-first flavor profile."}]', false, NULL);
INSERT INTO products (id, category_id, created_at, description, image_url, is_featured, name, price, stock, updated_at, brand, discount, images, original_price, shipping, specifications, tag, warranty, limited_time_price, limited_time_start_at, limited_time_end_at, status, detail_content, free_shipping, free_shipping_threshold) VALUES (8, 8, NULL, 'Soft bite-size chicken treats for puppy training, recall practice and positive reinforcement.', 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=900&q=80', false, 'CanineCore Puppy Training Treats', 12.90, 160, NULL, 'CanineCore', 24, '["https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=900&q=80"]', 16.90, 'Standard shipping', '{"Pet Size":"Small, Medium","Weight":"300 g","Flavor":"Chicken","Texture":"Soft"}', 'new', 'Freshness guarantee', NULL, NULL, NULL, 'ACTIVE', '[{"type":"text","content":"Small, soft rewards help keep training fast and focused."}]', false, NULL);

SET FOREIGN_KEY_CHECKS = 1;
