-- Bundle product sample data for the current shop schema.
-- Import after categories/brands exist, or run it against a fresh schema.

INSERT INTO categories (
    id, name, description, parent_id, level, image_url, localized_content
) VALUES
(9001, 'Bundle Samples', 'Demo root category for bundle products.', NULL, 1, 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=900&q=80', '{"en":{"name":"Bundle Samples","description":"Demo root category for bundle products."},"es":{"name":"Paquetes de muestra","description":"Categoria raiz de demostracion para paquetes."},"zh":{"name":"套装样例","description":"套装商品演示根分类。"}}'),
(9002, 'Feeding Bundles', 'Starter packs for feeders, bowls and feeding mats.', 9001, 2, 'https://images.unsplash.com/photo-1595433707802-6b2626ef1c91?auto=format&fit=crop&w=900&q=80', '{"en":{"name":"Feeding Bundles","description":"Starter packs for feeders, bowls and feeding mats."},"es":{"name":"Paquetes de alimentacion","description":"Paquetes iniciales para comederos, tazones y tapetes."},"zh":{"name":"喂食套装","description":"适合喂食器、食盆和餐垫的入门套装。"}}'),
(9003, 'Walking Bundles', 'Harness, leash and travel bundle combinations.', 9001, 2, 'https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?auto=format&fit=crop&w=900&q=80', '{"en":{"name":"Walking Bundles","description":"Harness, leash and travel bundle combinations."},"es":{"name":"Paquetes de paseo","description":"Combinaciones de arnes, correa y viaje."},"zh":{"name":"遛宠套装","description":"牵引、胸背和出行组合套装。"}}'),
(9004, 'Comfort Bundles', 'Beds, blankets and calming comfort sets.', 9001, 2, 'https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?auto=format&fit=crop&w=900&q=80', '{"en":{"name":"Comfort Bundles","description":"Beds, blankets and calming comfort sets."},"es":{"name":"Paquetes de confort","description":"Camas, mantas y sets de descanso."},"zh":{"name":"舒适套装","description":"宠物床、毯子和安抚用品组合。"}}'),
(9005, 'Grooming Bundles', 'Shampoo, brushes and hygiene essentials.', 9001, 2, 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=900&q=80', '{"en":{"name":"Grooming Bundles","description":"Shampoo, brushes and hygiene essentials."},"es":{"name":"Paquetes de aseo","description":"Champu, cepillos y articulos de higiene."},"zh":{"name":"美容清洁套装","description":"洗护、梳理和清洁用品组合。"}}')
ON DUPLICATE KEY UPDATE
name = VALUES(name),
description = VALUES(description),
parent_id = VALUES(parent_id),
level = VALUES(level),
image_url = VALUES(image_url),
localized_content = VALUES(localized_content);

INSERT INTO products (
    id,
    name,
    description,
    price,
    stock,
    category_id,
    image_url,
    status,
    brand,
    original_price,
    discount,
    limited_time_price,
    limited_time_start_at,
    limited_time_end_at,
    tag,
    images,
    specifications,
    detail_content,
    variants,
    warranty,
    shipping,
    free_shipping,
    free_shipping_threshold,
    is_featured
) VALUES
(9101,
 'Smart Feeding Starter Bundle',
 'A convenient starter set for daily feeding routines, built around an automatic feeder and matching bowls.',
 189.90,
 28,
 9002,
 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=900&q=80',
 'ACTIVE',
 'PawPilot',
 229.70,
 17,
 NULL,
 NULL,
 NULL,
 'hot',
 '["https://images.unsplash.com/photo-1601758123927-1967a0d5f11b?auto=format&fit=crop&w=900&q=80","https://images.unsplash.com/photo-1595433707802-6b2626ef1c91?auto=format&fit=crop&w=900&q=80"]',
 '{"bundle.enabled":"true","bundle.title":"Smart Feeding Starter Bundle","bundle.price":"159.90","bundle.items":"[{\\\"name\\\":\\\"Automatic feeder 4L\\\",\\\"quantity\\\":1},{\\\"name\\\":\\\"Stainless steel bowl\\\",\\\"quantity\\\":2},{\\\"name\\\":\\\"Silicone feeding mat\\\",\\\"quantity\\\":1}]","i18n.en.name":"Smart Feeding Starter Bundle","i18n.en.description":"A convenient starter set for daily feeding routines, built around an automatic feeder and matching bowls.","i18n.es.name":"Paquete inicial de alimentacion inteligente","i18n.es.description":"Un set inicial para rutinas diarias de alimentacion con comedero automatico y tazones a juego.","i18n.zh.name":"智能喂食入门套装","i18n.zh.description":"包含自动喂食器、食盆和餐垫的日常喂食入门组合。"}',
 '[{"type":"text","content":"Ideal for pet parents who want a ready-to-use feeding setup with one purchase."},{"type":"text","content":"Bundle pricing is recognized by the storefront through the bundle.* specification fields."}]',
 NULL,
 '1 year limited warranty',
 'Ships in a protective box.',
 FALSE,
 NULL,
 TRUE),
(9102,
 'Walk Ready Duo Bundle',
 'A balanced walking bundle with leash, harness and lightweight travel accessories for everyday outings.',
 84.90,
 46,
 9003,
 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=900&q=80',
 'ACTIVE',
 'TrailTails',
 104.60,
 19,
 NULL,
 NULL,
 NULL,
 'new',
 '["https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?auto=format&fit=crop&w=900&q=80","https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=900&q=80"]',
 '{"bundle.enabled":"true","bundle.title":"Walk Ready Duo Bundle","bundle.price":"69.90","bundle.items":"[{\\\"name\\\":\\\"No-pull harness\\\",\\\"quantity\\\":1},{\\\"name\\\":\\\"Reflective leash\\\",\\\"quantity\\\":1},{\\\"name\\\":\\\"Waste bag dispenser\\\",\\\"quantity\\\":1}]","i18n.en.name":"Walk Ready Duo Bundle","i18n.en.description":"A balanced walking bundle with leash, harness and lightweight travel accessories for everyday outings.","i18n.es.name":"Paquete listo para paseo","i18n.es.description":"Un paquete equilibrado para paseos diarios con arnes, correa y accesorios ligeros.","i18n.zh.name":"遛宠出行套装","i18n.zh.description":"包含胸背、牵引绳和出行小配件的日常遛宠组合。"}',
 '[{"type":"text","content":"A practical bundle for daily walks, training and short trips."},{"type":"text","content":"The reflective leash and no-pull harness are a good first purchase for new pet parents."}]',
 NULL,
 '1 year limited warranty',
 'Standard shipping',
 FALSE,
 NULL,
 FALSE),
(9103,
 'Comfort Rest Bundle',
 'An everyday comfort bundle with a calming bed, a blanket and a soft toy for rest and recovery.',
 149.90,
 22,
 9004,
 'https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?auto=format&fit=crop&w=900&q=80',
 'ACTIVE',
 'CloudNap',
 179.70,
 17,
 139.90,
 '2026-05-01 00:00:00',
 '2026-06-30 23:59:59',
 'discount',
 '["https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=80","https://images.unsplash.com/photo-1601758123927-1967a0d5f11b?auto=format&fit=crop&w=900&q=80"]',
 '{"bundle.enabled":"true","bundle.title":"Comfort Rest Bundle","bundle.price":"129.90","bundle.items":"[{\\\"name\\\":\\\"Orthopedic calming bed\\\",\\\"quantity\\\":1},{\\\"name\\\":\\\"Soft blanket\\\",\\\"quantity\\\":1},{\\\"name\\\":\\\"Plush comfort toy\\\",\\\"quantity\\\":1}]","i18n.en.name":"Comfort Rest Bundle","i18n.en.description":"An everyday comfort bundle with a calming bed, a blanket and a soft toy for rest and recovery.","i18n.es.name":"Paquete de descanso y confort","i18n.es.description":"Un paquete diario de descanso con cama calmante, manta y juguete suave.","i18n.zh.name":"舒适休息套装","i18n.zh.description":"包含安抚床、毯子和柔软玩具的休息护理组合。"}',
 '[{"type":"text","content":"Designed for pets that like to curl up and stay cozy through the night."},{"type":"text","content":"The limited-time price can be used to highlight a promotion banner on the storefront."}]',
 NULL,
 '1 year limited warranty',
 'Compressed shipping; allow 24 hours to expand.',
 TRUE,
 899.00,
 TRUE),
(9104,
 'Grooming Care Bundle',
 'A complete home grooming bundle with shampoo, brush, nail clipper and towel for routine care.',
 68.90,
 35,
 9005,
 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=900&q=80',
 'ACTIVE',
 'PurePaws',
 84.70,
 19,
 NULL,
 NULL,
 NULL,
 'new',
 '["https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=900&q=80","https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=900&q=80"]',
 '{"bundle.enabled":"true","bundle.title":"Grooming Care Bundle","bundle.price":"59.90","bundle.items":"[{\\\"name\\\":\\\"Sensitive skin shampoo\\\",\\\"quantity\\\":1},{\\\"name\\\":\\\"Slicker brush\\\",\\\"quantity\\\":1},{\\\"name\\\":\\\"Nail clipper\\\",\\\"quantity\\\":1},{\\\"name\\\":\\\"Quick-dry towel\\\",\\\"quantity\\\":1}]","i18n.en.name":"Grooming Care Bundle","i18n.en.description":"A complete home grooming bundle with shampoo, brush, nail clipper and towel for routine care.","i18n.es.name":"Paquete de aseo completo","i18n.es.description":"Un paquete de aseo para casa con champu, cepillo, cortaunas y toalla.","i18n.zh.name":"美容护理套装","i18n.zh.description":"包含洗护、梳理、修甲和擦干用品的家庭美容护理组合。"}',
 '[{"type":"text","content":"A useful bundle for weekly grooming sessions and quick hygiene routines."},{"type":"text","content":"It also works well as a gift bundle for first-time pet owners."}]',
 NULL,
 'Quality guarantee',
 'Standard shipping',
 FALSE,
 NULL,
 FALSE)
ON DUPLICATE KEY UPDATE
name = VALUES(name),
description = VALUES(description),
price = VALUES(price),
stock = VALUES(stock),
category_id = VALUES(category_id),
image_url = VALUES(image_url),
status = VALUES(status),
brand = VALUES(brand),
original_price = VALUES(original_price),
discount = VALUES(discount),
limited_time_price = VALUES(limited_time_price),
limited_time_start_at = VALUES(limited_time_start_at),
limited_time_end_at = VALUES(limited_time_end_at),
tag = VALUES(tag),
images = VALUES(images),
specifications = VALUES(specifications),
detail_content = VALUES(detail_content),
variants = VALUES(variants),
warranty = VALUES(warranty),
shipping = VALUES(shipping),
free_shipping = VALUES(free_shipping),
free_shipping_threshold = VALUES(free_shipping_threshold),
is_featured = VALUES(is_featured);
