import fs from 'fs';
import path from 'path';

const readFrontendRoot = (...segments: string[]) =>
  fs.readFileSync(path.join(__dirname, '..', '..', ...segments), 'utf8');

describe('commercial ops contracts', () => {
  it('keeps a runnable HTTP commercial smoke entry for live storefront+API gates', () => {
    const pkg = JSON.parse(readFrontendRoot('package.json'));
    const smoke = readFrontendRoot('scripts', 'commercial-http-smoke.js');

    expect(pkg.scripts['test:commercial-smoke']).toContain('commercial-http-smoke.js');
    expect(smoke).toContain('/api/products');
    expect(smoke).toContain('/api/payments/channels');
    expect(smoke).toContain('/api/app/config');
    expect(smoke).toContain('mexico payment rails present');
    expect(smoke).toContain('MERCADO_PAGO');
    expect(smoke).toContain('/checkout');
    expect(smoke).toContain('robots.txt');
    expect(smoke).toContain('/api/orders/checkout/guest');
    expect(smoke).toContain('/api/payments');
    expect(smoke).toContain('/api/orders/track');
    expect(smoke).toContain('guest checkout PENDING_PAYMENT');
    expect(smoke).toContain('guest checkout rate-limit handled');
    expect(smoke).toContain('skipped guest conversion after backoff retry');
    expect(smoke).toContain('payment has paymentUrl');
    expect(smoke).toContain('signPaymentCallback');
    expect(smoke).toContain('payment callback received');
    expect(smoke).toContain('mercado webhook endpoint live');
    expect(smoke).toContain('stripe webhook endpoint live');
    expect(smoke).toContain('mercado webhook alias endpoint live');
    expect(smoke).toContain('signMercadoPagoWebhook');
    expect(smoke).toContain('MERCADO_PAGO_WEBHOOK_SECRET');
    expect(smoke).toContain('mercado webhook invalid signature 400');
    expect(smoke).toContain('mercado webhook valid signature accepted');
    expect(smoke).toContain('mercado webhook signed path skipped');
    expect(smoke).toContain('signStripeWebhook');
    expect(smoke).toContain('STRIPE_WEBHOOK_SECRET');
    expect(smoke).toContain('stripe webhook invalid signature 400');
    expect(smoke).toContain('stripe webhook valid signature accepted');
    expect(smoke).toContain('stripe webhook signed path skipped');
    expect(smoke).toContain('paid payment status PAID');
    expect(smoke).toContain('auth register 200');
    expect(smoke).toContain('auth register rate-limit handled');
    expect(smoke).toContain('auth checkout 200');
    expect(smoke).toContain('auth payment create 200');
    expect(smoke).toContain('auth paid payment status PAID');
    expect(smoke).toContain('SHOPTEST_PAYMENT_CALLBACK_SECRET');
  });


  it('keeps commercial mobile-device viewport and production readiness smoke entries', () => {
    const pkg = JSON.parse(readFrontendRoot('package.json'));
    const mobile = readFrontendRoot('scripts', 'commercial-mobile-device-smoke.js');
    const production = readFrontendRoot('scripts', 'commercial-production-readiness.js');
    expect(pkg.scripts['test:commercial-mobile-device-smoke']).toContain('commercial-mobile-device-smoke.js');
    expect(pkg.scripts['test:commercial-production-readiness']).toContain('commercial-production-readiness.js');
    expect(mobile).toContain('320x568');
    expect(mobile).toContain('360x740');
    expect(mobile).toContain('390x844');
    expect(mobile).toContain('ShopTestAndroidApp');
    expect(mobile).toContain('primary touch targets >=44px');
    expect(mobile).toContain('[data-commercial-primary-cta]');
    expect(mobile).toContain('.shopee-hero__actions .home-btn');
    expect(mobile).toContain('sticky rail clear of bottom nav');
    expect(mobile).toContain('real-device APK/WebView install E2E remains required');
    expect(production).toContain('SHOPTEST_REQUIRE_PRODUCTION');
    expect(production).toContain('SHOPTEST_REQUIRE_COMMERCIAL_SHIP');
    expect(production).toContain('COMMERCIAL_SHIP_SOFT_GATES');
    expect(production).toContain('production host reachable');
    expect(production).toContain('production DNS A records');
    expect(production).toContain('production DNS AAAA records');
    expect(production).toContain('cloudflare origin gap diagnosis');
    expect(production).toContain('probeOriginEdgeDual');
    expect(production).toContain('origin edge CWV measurement');
    expect(production).toContain('SHOPTEST_PRODUCTION_HOST');
    expect(production).toContain('measureProductionCwv');
    expect(production).toContain('productionTlsInsecure');
    expect(production).toContain("const configuredLocalUiBase = String(process.env.SHOPTEST_UI_BASE || '').trim();");
    expect(production).toContain('SHOPTEST_UI_BASE not set; webhook contract probe skipped');
    expect(production).toContain('local stripe webhook rejects bad signature');
    expect(production).toContain('local mercado webhook rejects bad signature');
    expect(production).toContain('real provider webhook traffic evidence');
    expect(production).toContain('real-device mobile E2E evidence');
    expect(production).toContain('validateDeviceE2eEvidence');
    expect(production).toContain('device evidence sha256 mismatch with current mobile-version.json');
    expect(production).toContain('device launchExitCode');
    expect(production).toContain('SHOPTEST_DEVICE_E2E_MAX_AGE_DAYS');
    expect(production).toContain('COMMERCIAL_SHIP_BLOCKED');
    expect(production).toContain('local APK artifact integrity');
    expect(production).toContain('local mobile-version.json present');
    expect(production).toContain('probeLocalMobileReleaseArtifact');
  });

  it('keeps physical-device evidence recorder requiring install and launch success', () => {
    const recorder = readFrontendRoot('scripts', 'record-commercial-device-e2e.js');
    expect(recorder).toContain("adb', ['version']");
    expect(recorder).toContain("'install', '-r', apkPath");
    expect(recorder).toContain("'android.intent.category.LAUNCHER'");
    expect(recorder).toContain('const launchOk = launch.status === 0');
    expect(recorder).toContain("fail('adb launch failed')");
    expect(recorder).toContain('Commercial device install+launch recorded via adb for the current signed APK');
  });

  it('keeps cloudflare origin diagnose classifying wrong-origin and healthy-origin 522', () => {
    const diagnose = fs.readFileSync(
      path.join(__dirname, '..', '..', '..', 'scripts', 'diagnose-cloudflare-origin.sh'),
      'utf8',
    );
    expect(diagnose).toContain('external multiprobe note');
    expect(diagnose).toContain('200-wrong-origin');
    expect(diagnose).toContain('public_body_not_shopmx');
    expect(diagnose).toContain('Wrong/stale origin IP is the most common 522 cause');
    expect(diagnose).toContain('rapid4cloud');
    expect(diagnose).toContain('SHOPTEST_REQUIRE_PRODUCTION=1');
  });

  it('keeps checkout pure helpers modularized for commercial maintainability', () => {
    const helpers = fs.readFileSync(
      path.join(__dirname, 'checkoutHelpers.ts'),
      'utf8',
    );
    const checkout = fs.readFileSync(
      path.join(__dirname, '..', 'pages', 'Checkout.tsx'),
      'utf8',
    );
    expect(helpers).toContain('export const formatCheckoutDateTime');
    expect(helpers).toContain('export const getCheckoutCouponErrorMessage');
    expect(helpers).toContain('export const isValidCheckoutPostalCode');
    expect(helpers).toContain('export const normalizeCheckoutText');
    expect(helpers).toContain('export const hasCompleteCheckoutRecipientName');
    expect(helpers).toContain('export const estimateCouponDiscount');
    expect(helpers).toContain('export const deriveCheckoutShippingQuoteState');
    expect(helpers).toContain('export const deriveCheckoutGiftMetrics');
    expect(helpers).toContain('export const buildCheckoutShippingCopy');
    expect(helpers).toContain('export const resolveCheckoutSubmitState');
    expect(helpers).toContain('export const buildCheckoutMainShellProps');
    expect(helpers).toContain('export const buildCheckoutLoadingShellProps');
    expect(helpers).toContain('export const buildCheckoutPaymentPendingShellProps');
    expect(helpers).toContain('export const buildCheckoutPaymentActiveShellProps');
    expect(helpers).toContain('export const buildCheckoutCartLoadErrorShellProps');
    expect(helpers).toContain('export const buildCheckoutEmptyShellProps');
    expect(helpers).toContain('export const buildCheckoutPaymentUnavailableRecoveryDescriptors');
    expect(helpers).toContain('export const buildCheckoutSubmitActionLabel');
    expect(helpers).toContain('export const buildCheckoutConfirmationActionLabel');
    expect(helpers).toContain('export const buildCheckoutSubmitTooltip');
    expect(helpers).toContain('export const buildCheckoutSelectedAddressLabel');
    expect(helpers).toContain('export const buildCheckoutAddressGroupLabel');
    expect(helpers).toContain('export const buildCheckoutRegionInputLabel');
    expect(helpers).toContain('export const buildCheckoutCouponSelectLabel');
    expect(helpers).toContain('export const resolveCheckoutNewAddressReady');
    expect(helpers).toContain('export const resolveCheckoutSelectedAddressReady');
    expect(helpers).toContain('export const getRecommendedPaymentMethod');
    expect(helpers).toContain('export const resolveCheckoutPaymentMethod');
    expect(helpers).toContain('export const toSafeMoney');
    expect(helpers).toContain('export const normalizeStatusCode');
    expect(helpers).toContain('export const isCompleteSavedAddress');
    expect(helpers).toContain('export const isPurchasable');
    expect(helpers).toContain('export const isFinalCheckoutOrderError');
    expect(helpers).toContain('export const mergeHydratableCheckoutFields');
    expect(helpers).toContain('export const resolveGuestRestorePrice');
    expect(helpers).toContain('export const parseCheckoutPendingOrderSnapshot');
    expect(helpers).toContain('export const parseCheckoutPaymentPollResult');
    expect(helpers).toContain('export const PAYMENT_STATUS_LABEL_KEYS');
    expect(helpers).toContain('export const buildCheckoutValidationAnnouncement');
    expect(helpers).toContain('export const createCheckoutIdempotencyKey');
    expect(helpers).toContain('export const readCheckoutPendingOrder');
    expect(helpers).toContain('export const persistCheckoutPendingOrder');
    expect(helpers).toContain('export const readCheckoutGuestDraftFields');
    expect(checkout).toContain('getOrCreateCheckoutIdempotencyKey');
    expect(checkout).toContain('readCheckoutPendingOrder');
    expect(checkout).not.toContain('const createCheckoutIdempotencyKey = () => {');
    expect(checkout).not.toContain('const readCheckoutPendingOrder = () => {');
    expect(helpers).toContain('export const buildCheckoutFieldErrorMap');
    expect(helpers).toContain('export const normalizeCheckoutValidationMessage');
    expect(checkout).toContain('buildCheckoutValidationAnnouncement');
    expect(checkout).not.toContain('const buildCheckoutValidationAnnouncement = (');
    expect(checkout).toContain('resolveGuestRestorePrice');
    expect(checkout).toContain('parseCheckoutPendingOrderSnapshot');
    expect(checkout).not.toContain('const resolveGuestRestorePrice = (item: CartItem, product');
    expect(checkout).not.toContain('const parseCheckoutPendingOrderSnapshot = (raw: string | null)');
    expect(checkout).toContain('isCompleteSavedAddress');
    expect(checkout).toContain('isPurchasable');
    expect(checkout).not.toContain('const isCompleteSavedAddress = (address?: UserAddress | null) =>');
    expect(checkout).not.toContain('const isPurchasable = (item: CartItem) =>');
    expect(checkout).toContain("from '../utils/checkoutHelpers'");
    expect(checkout).toContain('formatCheckoutDateTime');
    expect(checkout).toContain('getCheckoutCouponErrorMessage');
    expect(checkout).toContain('normalizeCheckoutText');
    expect(checkout).toContain('estimateCouponDiscount');
    expect(checkout).toContain('resolveCheckoutPaymentMethod');
    expect(checkout).not.toContain('const normalizeCheckoutText = (value: unknown, maxLength: number) =>');
    expect(checkout).not.toContain('const estimateCouponDiscount = (coupon: UserCoupon, cartTotal: number) =>');
    expect(checkout).not.toContain('const getRecommendedPaymentMethod = (channels: PaymentChannel[], currency: string) =>');
    expect(checkout).toContain("from '../hooks/useCheckoutDerivedTotals'");
    expect(checkout).toContain('useCheckoutDerivedTotals({');
    expect(checkout).toContain('useCheckoutCartTotals(cartItems)');
    expect(checkout).not.toContain('const shippingQuoteFallbackActive = shippingQuoteFailed && !selectedUserCouponId;');
    expect(checkout).not.toContain('const checkoutSubmitDisabled = submitting');
    expect(checkout).toContain('buildCheckoutSubmitActionLabel');
        expect(checkout).toContain('buildCheckoutMainShellProps');
    expect(checkout).toContain('buildCheckoutLoadingShellProps({');
    expect(checkout).toContain('buildCheckoutPaymentPendingShellProps({');
    expect(checkout).toContain('buildCheckoutPaymentActiveShellProps({');
    expect(checkout).toContain('buildCheckoutCartLoadErrorShellProps({');
    expect(checkout).toContain('buildCheckoutEmptyShellProps({');
    expect(checkout).toContain('buildCheckoutPaymentUnavailableRecoveryDescriptors({');
expect(checkout).toContain('buildCheckoutConfirmationActionLabel');
    expect(checkout).toContain('buildCheckoutSubmitTooltip');
    expect(checkout).toContain('resolveCheckoutNewAddressReady');
    expect(checkout).toContain('resolveCheckoutSelectedAddressReady');
    expect(checkout).not.toContain("const checkoutSubmitActionLabel = shippingQuoteReady");
    expect(checkout).not.toContain("const checkoutConfirmationActionLabel = checkoutBlockingAction");
    const derived = fs.readFileSync(path.join(__dirname, '..', 'hooks', 'useCheckoutDerivedTotals.ts'), 'utf8');
    expect(derived).toContain('export const useCheckoutDerivedTotals');
    expect(derived).toContain('deriveCheckoutShippingQuoteState(');
    expect(derived).toContain('buildCheckoutShippingCopy(');
  });



  it('keeps checkout submit and guest restore pure guards modularized', () => {
    const helpers = fs.readFileSync(path.join(__dirname, 'checkoutHelpers.ts'), 'utf8');
    const checkout = fs.readFileSync(path.join(__dirname, '..', 'pages', 'Checkout.tsx'), 'utf8');
    const orderActions = fs.readFileSync(path.join(__dirname, '..', 'hooks', 'useCheckoutOrderActions.ts'), 'utf8');
    const checkoutSurface = `${checkout}
${orderActions}`;
    expect(helpers).toContain('export const buildGuestCheckoutOrderItems');
    expect(helpers).toContain('export const buildGuestRestoreCartLine');
    expect(helpers).toContain('export const resolveCheckoutCartSubmitGuard');
    expect(helpers).toContain('export const resolveCheckoutContactSubmitGuard');
    expect(orderActions).toContain('resolveCheckoutCartSubmitGuard({');
    expect(orderActions).toContain('resolveCheckoutContactSubmitGuard({');
    expect(orderActions).toContain('buildGuestCheckoutOrderItems(cartItems)');
    expect(checkoutSurface).toMatch(/paymentMethodDetails\.some\(\s*\(method\)\s*=>\s*method\.value === normalizedPaymentMethod\s*\)/);
  });



  it('keeps checkout form sections modularized outside the page shell', () => {
    const checkout = fs.readFileSync(path.join(__dirname, '..', 'pages', 'Checkout.tsx'), 'utf8');
    const mainShell = fs.readFileSync(path.join(__dirname, '..', 'components', 'checkout', 'CheckoutMainShell.tsx'), 'utf8');
    const formSections = fs.readFileSync(path.join(__dirname, '..', 'components', 'checkout', 'CheckoutFormSections.tsx'), 'utf8');
    expect(checkout).toContain("from '../components/checkout/CheckoutMainShell'");
    expect(checkout).toContain('<CheckoutMainShell');
    expect(checkout).not.toContain('CheckoutItemsCard');
    expect(checkout).not.toContain('checkout-page__giftCelebrationModal');
    expect(mainShell).toContain('export const CheckoutMainShell');
    expect(mainShell).toContain("from './CheckoutFormSections'");
    expect(mainShell).toContain("from './CheckoutConversionSections'");
    expect(mainShell).toContain('CheckoutItemsCard');
    expect(mainShell).toContain('CheckoutExpressPaymentGrid');
    expect(mainShell).toContain('CheckoutSubmitPaymentSection');
    expect(mainShell).toContain('checkout-page__giftCelebrationModal');
    expect(formSections).toContain('export const CheckoutItemsCard');
    expect(formSections).toContain('export const CheckoutExpressPaymentGrid');
    expect(formSections).toContain('export const CheckoutSubmitPaymentSection');
    expect(formSections).toContain('buildCheckoutPaymentUnavailableRecoveryDescriptors({');
    expect(formSections).toContain('checkout-page__mobilePayBar');
    expect(formSections).toContain('checkout-page__legalNotice');
    expect(formSections).toContain('data-checkout-payment-unavailable-recovery');
  });

  it('keeps checkout shell states modularized outside the page form shell', () => {
    const checkout = fs.readFileSync(path.join(__dirname, '..', 'pages', 'Checkout.tsx'), 'utf8');
    const shells = fs.readFileSync(path.join(__dirname, '..', 'components', 'checkout', 'CheckoutShellStates.tsx'), 'utf8');
    const helpers = fs.readFileSync(path.join(__dirname, 'checkoutHelpers.ts'), 'utf8');
    expect(checkout).toContain("from '../components/checkout/CheckoutShellStates'");
    expect(checkout).toContain('CheckoutLoadingShell');
    expect(checkout).toContain('CheckoutEmptyShell');
    expect(checkout).toContain('CheckoutPaymentActiveShell');
    expect(checkout).toContain('CheckoutPaymentPendingShell');
    expect(checkout).toContain('CheckoutCartLoadErrorShell');
    expect(shells).toContain('export const CheckoutLoadingShell');
    expect(shells).toContain('export const CheckoutEmptyShell');
    expect(shells).toContain('data-checkout-empty-actions');
    expect(shells).toContain('data-checkout-recovery-path="cart"');
    expect(shells).toContain('data-checkout-recovery-path="products"');
    expect(shells).toContain('data-checkout-recovery-path="coupons"');
    expect(shells).toContain('data-checkout-load-recovery');
    expect(helpers).toContain('export const buildCheckoutPaymentRecoveryCopy');
    expect(shells).toContain('buildCheckoutPaymentRecoveryCopy');
  });

  it('keeps checkout payment lifecycle modularized outside the page shell', () => {
    const checkout = fs.readFileSync(path.join(__dirname, '..', 'pages', 'Checkout.tsx'), 'utf8');
    const lifecycle = fs.readFileSync(path.join(__dirname, '..', 'hooks', 'useCheckoutPaymentLifecycle.ts'), 'utf8');
    expect(checkout).toContain("from '../hooks/useCheckoutPaymentLifecycle'");
    expect(checkout).toContain('useCheckoutPaymentLifecycle({');
    expect(checkout).not.toContain('const claimCheckoutPaymentPollLock');
    expect(lifecycle).toContain('export const useCheckoutPaymentLifecycle');
    expect(lifecycle).toContain('claimCheckoutPaymentPollLock');
    expect(lifecycle).toContain('startCheckoutPaymentPollWebLockSession');
    expect(lifecycle).toContain('writeCheckoutPaymentPollResult');
    expect(lifecycle).toContain('Checkout.pollPendingPayment');
    expect(lifecycle).toContain('Checkout.refreshSubmittedPayment');
    expect(lifecycle).toContain('CHECKOUT_PAYMENT_POLL_MAX_MS');
  });


  it('keeps product detail pure helpers, shell skeletons, and non-critical fetch modularized', () => {
    const page = fs.readFileSync(path.join(__dirname, '..', 'pages', 'ProductDetail.tsx'), 'utf8');
    const helpers = fs.readFileSync(path.join(__dirname, '..', 'pages', 'productDetailHelpers.tsx'), 'utf8');
    const shell = fs.readFileSync(path.join(__dirname, '..', 'pages', 'productDetailShell.tsx'), 'utf8');
    const nonCritical = fs.readFileSync(path.join(__dirname, '..', 'hooks', 'useProductDetailNonCriticalContent.ts'), 'utf8');
    const gallery = fs.readFileSync(path.join(__dirname, '..', 'hooks', 'useProductDetailGallery.ts'), 'utf8');
    const purchase = fs.readFileSync(path.join(__dirname, '..', 'hooks', 'useProductDetailPurchaseActions.ts'), 'utf8');
    const engagement = fs.readFileSync(path.join(__dirname, '..', 'hooks', 'useProductDetailEngagementActions.ts'), 'utf8');
    const community = fs.readFileSync(path.join(__dirname, '..', 'hooks', 'useProductDetailCommunityActions.ts'), 'utf8');
    const recommendation = fs.readFileSync(path.join(__dirname, '..', 'hooks', 'useProductDetailRecommendationActions.ts'), 'utf8');
    const recommendationsPanel = fs.readFileSync(path.join(__dirname, '..', 'pages', 'productDetailRecommendations.tsx'), 'utf8');
    const galleryPanel = fs.readFileSync(path.join(__dirname, '..', 'pages', 'productDetailGallery.tsx'), 'utf8');
    const summaryPanel = fs.readFileSync(path.join(__dirname, '..', 'pages', 'productDetailSummary.tsx'), 'utf8');
    const contentPanel = fs.readFileSync(path.join(__dirname, '..', 'pages', 'productDetailContent.tsx'), 'utf8');
    const buyBarPanel = fs.readFileSync(path.join(__dirname, '..', 'pages', 'productDetailBuyBar.tsx'), 'utf8');

    expect(page).toContain("from './productDetailHelpers'");
    expect(page).toContain("from './productDetailShell'");
    expect(page).toContain("from '../hooks/useProductDetailNonCriticalContent'");
    expect(page).toContain("from '../hooks/useProductDetailGallery'");
    expect(page).toContain("from '../hooks/useProductDetailPurchaseActions'");
    expect(page).toContain("from '../hooks/useProductDetailEngagementActions'");
    expect(page).toContain("from '../hooks/useProductDetailCommunityActions'");
    expect(page).toContain("from '../hooks/useProductDetailRecommendationActions'");
    expect(page).not.toContain("from './productDetailRecommendations'");
    expect(shell).toContain("from './productDetailRecommendations'");
    expect(page).toContain('useProductDetailNonCriticalContent({');
    expect(page).toContain('useProductDetailGallery({');
    expect(page).toContain('useProductDetailPurchaseActions({');
    expect(page).toContain('useProductDetailEngagementActions({');
    expect(page).toContain('useProductDetailCommunityActions({');
    expect(page).toContain('useProductDetailRecommendationActions({');
    expect(page).not.toContain('<ProductDetailRecommendations');
    expect(shell).toContain('<ProductDetailRecommendations');
    expect(summaryPanel).toContain('<ProductDetailCompleteSet');
    expect(recommendationsPanel).toContain('export const ProductDetailCompleteSet');
    expect(page).toContain('buildRelatedRecommendations');
    expect(page).toContain('warmNonCriticalContent');
    expect(page).toContain('handleAddToCart');
    expect(page).toContain('handleBuyNow');
    expect(page).toContain('selectGalleryImage');
    expect(page).toContain('handleFavorite');
    expect(page).toContain('handleAskQuestion');
    expect(helpers).toContain('export const normalizeProductDetailTab');
    expect(helpers).toContain('export const normalizeQuestionText');
    expect(helpers).toContain('export const PRODUCT_SIZE_CALCULATOR_MAX_WEIGHT_KG = 200;');
    expect(helpers).toContain('export const findSelectedProductVariant');
    expect(helpers).toContain('export const buildSelectedSpecsPayload');
    expect(shell).toContain('export const ProductDetailSkeleton');
    expect(shell).toContain('export const ProductDetailLazyFallback');
    expect(nonCritical).toContain('export const useProductDetailNonCriticalContent');
    expect(nonCritical).toContain('const fetchReviews = useCallback(async (requestSeq: number) => {');
    expect(nonCritical).toContain('const warmNonCriticalContent = useCallback((requestSeq: number) => {');
    expect(gallery).toContain('export const useProductDetailGallery');
    expect(gallery).toContain('const selectGalleryImage = (image: string, index: number) => {');
    expect(gallery).toContain('Avoid background carousel timers in tests');
    expect(purchase).toContain('export const useProductDetailPurchaseActions');
    expect(purchase).toContain('const handleAddToCart = async () => {');
    expect(purchase).toContain('const handleBuyNow = async () => {');
    expect(engagement).toContain('export const useProductDetailEngagementActions');
    expect(engagement).toContain('const handleFavorite = async () => {');
    expect(engagement).toContain('const handleStockAlert = () => {');
    expect(engagement).toContain('const handleCompare = () => {');
    expect(community).toContain('export const useProductDetailCommunityActions');
    expect(community).toContain('const handleAddReview = async (orderId: number, rating: number, comment: string, imageUrls: string[] = []) => {');
    expect(community).toContain('const handleAskQuestion = async () => {');
    expect(recommendation).toContain('export const useProductDetailRecommendationActions');
    expect(recommendation).toContain('const handleAddRecommendationToCart = async (');
    expect(helpers).toContain('export const isRecommendationUnavailable');
    expect(helpers).toContain('export const buildRelatedRecommendations');
        expect(helpers).toContain('export const buildCompleteSetItems');
    expect(helpers).toContain('export const deriveProductDetailPricing');
    expect(helpers).toContain('export const deriveProductDetailSelectionState');
    expect(helpers).toContain('export const deriveProductDetailActionBlockState');
    expect(helpers).toContain('export const buildProductDetailActionLabels');
    expect(helpers).toContain('export const buildProductDetailPurchaseReadinessData');
    expect(helpers).toContain('export const buildProductDetailShippingCopy');
    expect(helpers).toContain('export const buildProductDetailFitGuidance');
    expect(helpers).toContain('export const resolveProductDetailCartActionLabels');
    expect(helpers).toContain('export const shouldShowProductDetailDecisionChecklist');
    expect(helpers).toContain('export const resolveProductDetailLowStockUrgencyLabel');
    expect(helpers).toContain('export const buildProductDetailMobileBuybarPresentation');
    expect(helpers).toContain('export const withProductDetailChecklistIcons');
    expect(helpers).toContain('export const buildProductDetailMainShellProps');
    expect(helpers).toContain('export const buildProductDetailLoadingShellProps');
    expect(helpers).toContain('export const buildProductDetailLoadErrorShellProps');
    expect(helpers).toContain('export const buildProductDetailNotFoundShellProps');
    expect(helpers).toContain('export const resolveProductDetailPageTitle');
    expect(helpers).toContain('export const resolveProductDetailSeoDescription');
    expect(helpers).toContain('export const resolveProductDetailSeoImage');
    expect(helpers).toContain('export const resolveProductDetailVariantGallerySelection');
    expect(page).toContain('buildProductDetailLoadingShellProps({');
    expect(page).toContain('buildProductDetailLoadErrorShellProps({');
    expect(page).toContain('buildProductDetailNotFoundShellProps({');
    expect(page).toContain('resolveProductDetailPageTitle({');
    expect(page).toContain('resolveProductDetailSeoDescription({');
    expect(page).toContain('resolveProductDetailSeoImage({');
    expect(page).toContain('resolveProductDetailVariantGallerySelection({');
    expect(page).toContain('deriveProductDetailPricing({');
    expect(page).toContain('deriveProductDetailSelectionState({');
    expect(page).toContain('deriveProductDetailActionBlockState({');
    expect(page).toContain('buildProductDetailActionLabels({');
    expect(page).toContain('buildProductDetailShippingCopy({');
    expect(page).toContain('buildProductDetailFitGuidance({');
    expect(page).toContain('shouldShowProductDetailDecisionChecklist({');
    expect(page).toContain('resolveProductDetailLowStockUrgencyLabel({');
    expect(page).toContain('buildProductDetailMobileBuybarPresentation({');
    expect(page).toContain('withProductDetailChecklistIcons(');
    expect(page).toContain('buildProductDetailMainShellProps({');
    expect(page).not.toContain("const lowStockUrgencyLabel = isLowStock");
    expect(page).not.toContain('const mobileBuybarPrice = formatMoney(displayPrice);');
    expect(page).not.toContain('const addToCartBlocked = isOutOfStock || purchaseSelectionBlocked || purchaseSubmitting !== null;');
    expect(page).not.toContain('const activePrice = selectedVariant?.price ?? product.effectivePrice ?? product.price;');
expect(recommendationsPanel).toContain('export const ProductDetailRecommendations');
    expect(recommendationsPanel).toContain('product-recommendations--strip');
    expect(page).not.toContain('product-recommendations--strip');
    expect(galleryPanel).toContain('export const ProductDetailGallery');
    expect(galleryPanel).toContain('export const ProductDetailImagePreviewModal');
    expect(galleryPanel).toContain('product-detail-main-image');
    expect(galleryPanel).toContain('product-gallery-controls__pause');
    expect(page).toContain("from './productDetailShell'");
    expect(page).toContain('<ProductDetailMainShell');
    expect(page).toContain('<ProductDetailLoadErrorShell');
    expect(page).toContain('<ProductDetailNotFoundShell');
    expect(page).not.toContain("from './productDetailGallery'");
    expect(page).not.toContain('<ProductDetailGallery');
    expect(page).not.toContain('<ProductDetailImagePreviewModal');
    expect(page).not.toContain('className="product-detail-main-image"');
    expect(page).not.toContain('product-gallery-controls__pause');
    expect(shell).toContain('export const ProductDetailMainShell');
    expect(shell).toContain("from './productDetailGallery'");
    expect(shell).toContain('<ProductDetailGallery');
    expect(shell).toContain('<ProductDetailImagePreviewModal');
    expect(shell).toContain('export const ProductDetailLoadErrorShell');
    expect(shell).toContain('export const ProductDetailNotFoundShell');
    expect(shell).toContain('data-product-detail-load-recovery');
    expect(summaryPanel).toContain('export const ProductDetailSummary');
    expect(summaryPanel).toContain('product-detail__summary');
    expect(summaryPanel).toContain('<ProductDetailMobileBuyBar');
    expect(summaryPanel).toContain("from './productDetailBuyBar'");
    expect(summaryPanel).toContain('product-purchase-readiness');
    expect(summaryPanel).toContain('product-options-anchor');
    expect(summaryPanel).toContain('export const ProductDetailSizeGuideModal');
    expect(summaryPanel).toContain('product-detail__sizeGuideModalRoot');
    expect(buyBarPanel).toContain('export const ProductDetailMobileBuyBar');
    expect(buyBarPanel).toContain('product-mobile-buybar');
    expect(buyBarPanel).toContain('product-mobile-buybar__cart');
    expect(buyBarPanel).toContain('product-mobile-buybar__buy');
    expect(page).toContain('<ProductDetailSizeGuideModal');
    expect(page).toContain("from './productDetailSummary'");
    expect(shell).not.toContain('<ProductDetailSizeGuideModal');
    expect(page).not.toContain('<ProductDetailSummary');
    expect(shell).toContain("from './productDetailSummary'");
    expect(shell).toContain('<ProductDetailSummary');
    expect(page).not.toContain('className="product-detail__summary"');
    expect(page).not.toContain('className="product-mobile-buybar"');
    expect(summaryPanel).not.toContain('className="product-mobile-buybar"');
    expect(contentPanel).toContain('export const ProductDetailContent');
    expect(contentPanel).toContain('product-tabs-card');
    expect(contentPanel).toContain('product-review-card');
    expect(contentPanel).toContain('product-qa-card');
    expect(page).not.toContain("from './productDetailContent'");
    expect(page).not.toContain('<ProductDetailContent');
    expect(shell).toContain("from './productDetailContent'");
    expect(shell).toContain('<ProductDetailContent');
    expect(page).not.toContain('className="product-tabs-card"');
    expect(page).not.toContain('className="product-qa-card"');
    expect(page).not.toContain('const handleAddRecommendationToCart = async (event: React.MouseEvent<HTMLElement>, item: Product) => {');
    expect(page).not.toContain('const fetchReviews = useCallback(async (requestSeq: number) => {');
    expect(page).not.toContain('const ProductDetailSkeleton: React.FC');
    expect(page).not.toContain('const handleAddToCart = async () => {');
    expect(page).not.toContain('const selectGalleryImage = (image: string, index: number) => {');
    expect(page).not.toContain('const handleFavorite = async () => {');
    expect(page).not.toContain('const handleAskQuestion = async () => {');
  });

  it('keeps cart loading, load-recovery, and full-empty shells modularized outside the page shell', () => {
    const page = fs.readFileSync(path.join(__dirname, '..', 'pages', 'Cart.tsx'), 'utf8');
    const shell = fs.readFileSync(path.join(__dirname, '..', 'pages', 'cartShellStates.tsx'), 'utf8');
    const panels = fs.readFileSync(path.join(__dirname, '..', 'pages', 'cartConversionPanels.tsx'), 'utf8');
    const lineItems = fs.readFileSync(path.join(__dirname, '..', 'pages', 'cartLineItems.tsx'), 'utf8');
    const savedPanel = fs.readFileSync(path.join(__dirname, '..', 'pages', 'cartSavedPanel.tsx'), 'utf8');
    const overview = fs.readFileSync(path.join(__dirname, '..', 'pages', 'cartOverviewPanels.tsx'), 'utf8');

    expect(page).toContain("from './cartHelpers'");
    expect(page).toContain("from './cartShellStates'");
    expect(page).toContain("from './cartConversionPanels'");
    expect(page).toContain("from './cartLineItems'");
    expect(page).toContain("from './cartSavedPanel'");
    expect(page).toContain("from './cartOverviewPanels'");
    expect(page).toContain("from '../hooks/useCartSessionData'");
    expect(page).toContain('useCartSessionData({');
    expect(page).not.toContain('const fetchCartItems = useCallback');
    expect(page).not.toContain('const RECENT_PRODUCTS_CACHE_MS');
    const helpers = fs.readFileSync(path.join(__dirname, '..', 'pages', 'cartHelpers.ts'), 'utf8');
    const session = fs.readFileSync(path.join(__dirname, '..', 'hooks', 'useCartSessionData.ts'), 'utf8');
    expect(helpers).toContain('export const clearRecentProductsCache');
    expect(helpers).toContain('export const deriveCartCheckoutMetrics');
    expect(helpers).toContain('export const buildCartActionLabels');
    expect(helpers).toContain('export const buildCartHeroHighlightDescriptors');
    expect(helpers).toContain('export const buildCartSummaryCardDescriptors');
    expect(helpers).toContain('export const resolveCartNextActionDescriptor');
    expect(helpers).toContain('export const buildCartShippingPresentation');
    expect(page).toContain('buildCartActionLabels({');
    expect(page).toContain('resolveCartNextActionDescriptor({');
    expect(page).toContain('buildCartShippingPresentation({');
    expect(page).not.toContain('const freeShippingRemainingText = (amount: number)');
    expect(page).not.toContain('const freeShippingProgressText = freeShippingUnlocked');
    expect(page).not.toContain('const retryCartLoadActionLabel =');
    expect(page).not.toContain('const cartNextAction = (() => {');
    expect(session).toContain('export const useCartSessionData');
    expect(session).toContain('const fetchCartItems = useCallback');
    expect(page).toContain('<CartLoadingState');
    expect(page).toContain('<CartLoadErrorState');
    expect(page).toContain('<CartFullEmptyState');
    expect(page).toContain('<CartPaymentReturnBanner');
    expect(page).toContain('<CartOrderSummary');
    expect(page).toContain('<CartInlineEmptyPanel');
    expect(page).toContain('<CartLineItems');
    expect(page).toContain('<CartSavedPanel');
    expect(page).toContain('<CartHeroOverview');
    expect(page).toContain('<CartRecentRecoveryPanel');
    expect(page).toContain('<CartBulkReadinessPanel');
    expect(page).not.toContain('className="cart-page__loadingStat shimmer"');
    expect(page).not.toContain('data-cart-load-recovery="true"');
    expect(page).not.toContain('className="cart-page__emptyHero"');
    expect(page).not.toContain('className="cart-page__paymentReturn"');
    expect(page).not.toContain('className="cart-page__summary"');
    expect(page).not.toContain('data-cart-empty-panel-actions="true"');
    expect(page).not.toContain('className="cart-page__table"');
    expect(page).not.toContain('className="cart-page__mobileList"');
    expect(page).not.toContain('className="cart-page__savedCard"');
    expect(page).not.toContain('className="cart-page__hero"');
    expect(page).not.toContain('className="cart-page__summaryStrip"');
    expect(page).not.toContain('className="cart-page__bulkActions"');
    expect(page).not.toContain('className="cart-page__recentRecovery"');
    expect(shell).toContain('export const CartLoadingState');
    expect(shell).toContain('export const CartLoadErrorState');
    expect(shell).toContain('export const CartFullEmptyState');
    expect(shell).toContain('data-cart-load-recovery="true"');
    expect(shell).toContain('data-cart-empty-actions="true"');
    expect(shell).toContain('cart-page__emptyHero');
    expect(shell).toContain('cart-page__loadingStat');
    expect(panels).toContain('export const CartPaymentReturnBanner');
    expect(panels).toContain('export const CartOrderSummary');
    expect(panels).toContain('export const CartInlineEmptyPanel');
    expect(panels).toContain('cart-page__paymentReturn');
    expect(panels).toContain('cart-page__summary');
    expect(panels).toContain('cart-page__trustBar');
    expect(panels).toContain('data-cart-empty-panel-actions="true"');
    expect(lineItems).toContain('export const CartLineItems');
    expect(lineItems).toContain('cart-page__table');
    expect(lineItems).toContain('cart-page__mobileList');
    expect(lineItems).toContain('cart-page__quantityStepper');
    expect(savedPanel).toContain('export const CartSavedPanel');
    expect(savedPanel).toContain('cart-page__savedCard');
    expect(savedPanel).toContain('cart-page__savedEmptyInner');
    expect(overview).toContain('export const CartHeroOverview');
    expect(overview).toContain('export const CartRecentRecoveryPanel');
    expect(overview).toContain('export const CartBulkReadinessPanel');
    expect(overview).toContain('cart-page__hero');
    expect(overview).toContain('cart-page__summaryStrip');
    expect(overview).toContain('cart-page__bulkActions');
    expect(overview).toContain('cart-page__recentRecovery');
  });

  it('keeps product list helpers and card modules outside the page shell', () => {
    const page = fs.readFileSync(path.join(__dirname, '..', 'pages', 'ProductList.tsx'), 'utf8');
    const helpers = fs.readFileSync(path.join(__dirname, '..', 'pages', 'productListHelpers.ts'), 'utf8');
    const card = fs.readFileSync(path.join(__dirname, '..', 'pages', 'productListCard.tsx'), 'utf8');
    const panels = fs.readFileSync(path.join(__dirname, '..', 'pages', 'productListPanels.tsx'), 'utf8');
    const modals = fs.readFileSync(path.join(__dirname, '..', 'pages', 'productListModals.tsx'), 'utf8');
    const shell = fs.readFileSync(path.join(__dirname, '..', 'pages', 'productListShellPanels.tsx'), 'utf8');
    expect(page).toContain("from './productListHelpers'");
    expect(page).toContain("from './productListPanels'");
    expect(page).toContain("from './productListShellPanels'");
    expect(page).toContain('<ProductListMainShell');
    expect(page).not.toContain("from './productListModals'");
    expect(page).not.toContain('<ProductListResultsGrid');
    expect(page).not.toContain('<ProductListFilterDrawer');
    expect(page).not.toContain('<ProductListLoadingPanel');
    expect(page).not.toContain('<ProductListLoadRecoveryPanel');
    expect(page).not.toContain('<ProductListEmptyPanel');
    expect(page).not.toContain('<ProductListModals');
    expect(page).not.toContain('product-list__heroBand');
    expect(page).not.toContain('product-list__smartBar');
    expect(page).not.toContain('const ProductListConfidenceStrip');
    expect(page).not.toContain('const ProductListCard = React.memo');
    expect(page).not.toContain('const PRODUCT_LIST_PAGE_SIZE = 12');
    expect(page).not.toContain('className="product-list__loading"');
    expect(page).not.toContain('data-product-list-load-recovery="true"');
    expect(page).not.toContain('data-product-list-empty-actions="true"');
    expect(page).not.toContain('className="product-list__filterDrawerRoot"');
    expect(page).not.toContain('product-list__quickAddModalRoot');
    expect(page).not.toContain('product-list__previewModalRoot');
    expect(helpers).toContain('export const PRODUCT_LIST_PAGE_SIZE');
    expect(helpers).toContain('export const clearProductListSessionCaches');
    expect(helpers).toContain('export const getPrice');
    expect(helpers).toContain('export const isQuickAddReady');
    expect(helpers).toContain('export const deriveProductListCatalogPresentation');
    expect(helpers).toContain('export const buildProductListActionLabels');
    expect(helpers).toContain('export const buildProductListActiveRefinementTagData');
    expect(helpers).toContain('export const buildProductListMobileDiscoveryDescriptors');
    expect(helpers).toContain('export const buildProductListEmptyDiscoveryDescriptors');
    expect(helpers).toContain('export const buildProductListMobileNextStepDescriptors');
    expect(helpers).toContain('export const buildProductListActiveResultContextDescriptors');
    expect(helpers).toContain('export const buildProductListMainShellProps');
    expect(helpers).toContain('export const buildProductListPetSizeOptions');
    expect(helpers).toContain('export const buildProductListMaterialOptions');
    expect(helpers).toContain('export const buildProductListColorOptions');
    expect(helpers).toContain('export const buildProductListOptionLabelMap');
    expect(helpers).toContain('export const deriveProductListVisibleCategories');
    expect(helpers).toContain('export const buildProductListSortOptions');
    expect(page).toContain('deriveProductListCatalogPresentation({');
    expect(page).toContain('buildProductListActionLabels({');
    expect(page).toContain('buildProductListMobileDiscoveryDescriptors({');
    expect(page).toContain('buildProductListEmptyDiscoveryDescriptors({');
    expect(page).toContain('buildProductListMobileNextStepDescriptors({');
    expect(page).toContain('buildProductListActiveResultContextDescriptors({');
    expect(page).toContain('buildProductListMainShellProps({');
    expect(page).toContain('buildProductListPetSizeOptions(');
    expect(page).toContain('buildProductListMaterialOptions(');
    expect(page).toContain('buildProductListColorOptions(');
    expect(page).toContain('buildProductListOptionLabelMap({');
    expect(page).toContain('deriveProductListVisibleCategories({');
    expect(page).not.toContain("label: t('pages.profile.petSizeSmall')");
    expect(page).not.toContain('const visibleCategories = useMemo(() => {');
    expect(page).not.toContain("const emptyDiscoveryActions: ProductListDiscoveryAction[] = [");
    expect(page).not.toContain('const mobileNextStepActions = filteredProducts.length === 0');
    expect(page).not.toContain('const activeResultContextActions = [');
    expect(card).toContain('export const ProductListCard');
    expect(card).toContain('export const ProductListConfidenceStrip');
    expect(card).toContain('className="product-list__card"');
    expect(card).toContain('product-list__confidenceStrip');
    expect(panels).toContain('export const ProductListFilterPanel');
    expect(panels).toContain('export const ProductListCategoryPanel');
    expect(panels).toContain('export const ProductListFilterDrawer');
    expect(panels).toContain('export const ProductListLoadingPanel');
    expect(panels).toContain('export const ProductListLoadRecoveryPanel');
    expect(panels).toContain('export const ProductListEmptyPanel');
    expect(panels).toContain('export const ProductListResultsGrid');
    expect(panels).toContain('data-product-list-load-recovery="true"');
    expect(panels).toContain('data-product-list-empty-actions="true"');
    expect(modals).toContain('export const ProductListModals');
    expect(modals).toContain('export const ProductListQuickAddModal');
    expect(modals).toContain('export const ProductListPreviewModal');
    expect(modals).toContain('product-list__quickAddModalRoot');
    expect(modals).toContain('product-list__previewModalRoot');
    expect(shell).toContain('export const ProductListMainShell');
    expect(shell).toContain("from './productListPanels'");
    expect(shell).toContain("from './productListModals'");
    expect(shell).toContain('<ProductListResultsGrid');
    expect(shell).toContain('<ProductListFilterDrawer');
    expect(shell).toContain('<ProductListLoadingPanel');
    expect(shell).toContain('<ProductListLoadRecoveryPanel');
    expect(shell).toContain('<ProductListEmptyPanel');
    expect(shell).toContain('<ProductListModals');
    expect(shell).toContain('product-list__heroBand');
    expect(shell).toContain('product-list__smartBar');
    expect(page).toContain("from '../hooks/useProductListCatalog'");
    expect(page).toContain("from '../hooks/useProductListProductActions'");
    expect(page).toContain("from '../hooks/useProductListSessionData'");
    expect(page).toContain("from '../hooks/useProductListNavigation'");
    expect(page).toContain("from '../hooks/useProductListDerivedCatalog'");
    expect(page).toContain('useProductListCatalog({');
    expect(page).toContain('useProductListProductActions({');
    expect(page).toContain('useProductListSessionData({');
    expect(page).toContain('useProductListNavigation({');
    expect(page).toContain('useProductListDerivedCatalog({');
    expect(page).not.toContain('const fetchProducts = useCallback');
    expect(page).not.toContain('const handleWishlistToggle = useCallback');
    expect(page).not.toContain('const submitQuickAdd = async () => {');
    expect(page).not.toContain('const buildProductsUrl = useCallback');
    expect(page).not.toContain('const handleSearch = (value: string)');
    expect(page).not.toContain('const handleAuthSessionChanged');
    expect(page).not.toContain('categoryApi.getTopLevel()');
    expect(page).not.toContain('productApi.getPersonalizedRecommendations()');
    expect(page).not.toContain('const getPersonalizedSortScore = (product: Product)');
    expect(page).not.toContain('const filteredProducts = useMemo(() => collectionProducts.filter');
    expect(helpers).toContain('export const filterProductsByRefinements');
    expect(helpers).toContain('export const sortProductList');
    expect(helpers).toContain('export const getPersonalizedSortScore');
    expect(helpers).toContain('export const deriveProductListInsights');
    const derived = fs.readFileSync(path.join(__dirname, '..', 'hooks', 'useProductListDerivedCatalog.ts'), 'utf8');
    expect(derived).toContain('export const useProductListDerivedCatalog');
    expect(derived).toContain('sortProductList(');
    expect(derived).toContain('filterProductsByRefinements(');
  });

  it('keeps home pure helpers and shell states modularized outside the page shell', () => {
    const page = fs.readFileSync(path.join(__dirname, '..', 'pages', 'Home.tsx'), 'utf8');
    const helpers = fs.readFileSync(path.join(__dirname, '..', 'pages', 'homeHelpers.tsx'), 'utf8');
    const shells = fs.readFileSync(path.join(__dirname, '..', 'pages', 'homeShellStates.tsx'), 'utf8');
    const firstFold = fs.readFileSync(path.join(__dirname, '..', 'pages', 'homeFirstFoldPanels.tsx'), 'utf8');
    const productPanels = fs.readFileSync(path.join(__dirname, '..', 'pages', 'homeProductPanels.tsx'), 'utf8');
    expect(page).toContain("from './homeHelpers'");
    expect(helpers).toContain('export const buildHomeGuestJourneyDescriptors');
    expect(helpers).toContain('export const buildHomeMobileQuickActionDescriptors');
    expect(helpers).toContain('export const deriveHomePromoProducts');
    expect(helpers).toContain('export const deriveHomeBestSellers');
    expect(helpers).toContain('export const deriveHomeDiscoveryProducts');
    expect(helpers).toContain('export const deriveHomeLocalPersonalizedProducts');
    expect(helpers).toContain('export const resolveHomePetUploadButtonLabel');
    expect(helpers).toContain('export const resolveHomePersonalizedPreferenceLabel');
    expect(helpers).toContain('export const buildHomePetGalleryItems');
    expect(page).toContain('buildHomeGuestJourneyDescriptors({');
    expect(page).toContain('buildHomeMobileQuickActionDescriptors({');
    expect(page).toContain('deriveHomePromoProducts(');
    expect(page).toContain('deriveHomeBestSellers(');
    expect(page).toContain('deriveHomeDiscoveryProducts({');
    expect(page).toContain('deriveHomeLocalPersonalizedProducts({');
    expect(page).toContain('resolveHomePetUploadButtonLabel({');
    expect(page).toContain('resolveHomePersonalizedPreferenceLabel({');
    expect(page).toContain('buildHomePetGalleryItems({');
    expect(helpers).toContain('export const buildHomeHeroSpotlightDescriptors');
    expect(helpers).toContain('export const buildHomeConversionHighlightDescriptors');
    expect(helpers).toContain('export const buildHomeStoryCardDescriptors');
    expect(helpers).toContain('export const resolveHomeHeroFeaturedProduct');
    expect(helpers).toContain('export const buildHomeHeroFeaturedTag');
    expect(page).toContain('buildHomeHeroSpotlightDescriptors({');
    expect(page).toContain('buildHomeConversionHighlightDescriptors({');
    expect(page).toContain('buildHomeStoryCardDescriptors({');
    expect(page).toContain('resolveHomeHeroFeaturedProduct({');
    expect(page).toContain('buildHomeHeroFeaturedTag({');
    expect(page).not.toContain("key: 'recommendations',");
    expect(page).not.toContain("key: 'starter',");
    expect(page).not.toContain("key: 'register',");
    expect(page).not.toContain("key: 'orders',");
    expect(page).not.toContain('const getPrice = (product: Product)');
    expect(page).not.toContain('const getDiscountPercent = (product: Product)');
    expect(page).toContain("from './homeShellStates'");
    expect(page).toContain("from './homeFirstFoldPanels'");
    expect(page).toContain("from './homeProductPanels'");
    expect(page).toContain("from '../hooks/useHomeCatalog'");
    expect(page).toContain("from '../hooks/useHomeProductActions'");
    expect(page).toContain('useHomeCatalog({');
    expect(page).toContain('useHomeProductActions({');
    expect(page).not.toContain('const fetchHome = async () => {');
    expect(page).not.toContain('const handleQuickAddToCart = async');
    expect(page).not.toContain('const handleQuickWishlist = async');
    expect(page).not.toContain('const addPersonalizedReadyProducts = async () => {');
    expect(page).not.toContain('const refreshPetGallery = useCallback');
    expect(page).toContain('<HomeLoadingShell');
    expect(page).toContain('<HomeLoadRecoveryShell');
    expect(page).toContain('<HomeHeroSection');
    expect(page).toContain('<HomeMobileQuickPanel');
    expect(page).toContain('<HomeTrustStrip');
    expect(page).toContain('<HomeConversionActionsSection');
    expect(page).toContain('<HomeStoryGrid');
    expect(page).toContain('<HomeBestSellersSection');
    expect(page).toContain('<HomeEditorialBand');
    expect(page).toContain('<HomePersonalizedProductsSection');
    expect(page).toContain('<HomeCategoriesSection');
    expect(page).toContain('<HomeRecentlyViewedSection');
    expect(page).toContain('<HomeFlashOffersSection');
    expect(page).toContain('<HomeDiscoverySection');
    expect(page).not.toContain('const DISCOVERY_BATCH_SIZE = 12');
    expect(page).not.toContain('const HomeIcon: React.FC');
    expect(page).not.toContain('data-home-loading-shell="true"');
    expect(page).not.toContain('data-home-load-recovery="true"');
    expect(page).not.toContain('className="shopee-hero"');
    expect(page).not.toContain('className="pet-trust-strip"');
    expect(page).not.toContain('className="shopee-section shopee-promo-products shopee-best-sellers"');
    expect(page).not.toContain('className="shopee-section shopee-editorial-band"');
    expect(page).not.toContain('className="shopee-section shopee-discovery shopee-for-you"');
    expect(page).not.toContain('className="shopee-section shopee-categories-section"');
    expect(page).not.toContain('data-home-empty-products="true"');
    expect(helpers).toContain('export const DISCOVERY_BATCH_SIZE');
    expect(helpers).toContain('export const resolveHomeCatalogBootstrap');
    expect(helpers).toContain('export const resolvePetGalleryImage');
    expect(helpers).toContain('export const HomeIcon');
    expect(shells).toContain('export const HomeLoadingShell');
    expect(shells).toContain('export const HomeLoadRecoveryShell');
    expect(shells).toContain('data-home-loading-shell="true"');
    expect(shells).toContain('data-home-load-recovery="true"');
    expect(firstFold).toContain('export const HomeHeroSection');
    expect(firstFold).toContain('export const HomeTrustStrip');
    expect(firstFold).toContain('export const HomeConversionActionsSection');
    expect(firstFold).toContain('className="shopee-hero"');
    expect(firstFold).toContain('className="pet-trust-strip"');
    expect(productPanels).toContain('export const HomeBestSellersSection');
    expect(productPanels).toContain('export const HomeEditorialBand');
    expect(productPanels).toContain('export const HomePersonalizedProductsSection');
    expect(productPanels).toContain('export const HomeCategoriesSection');
    expect(productPanels).toContain('export const HomeRecentlyViewedSection');
    expect(productPanels).toContain('export const HomeFlashOffersSection');
    expect(productPanels).toContain('export const HomeDiscoverySection');
    expect(productPanels).toContain('className="shopee-section shopee-promo-products shopee-best-sellers"');
    expect(productPanels).toContain('className="shopee-section shopee-discovery shopee-for-you"');
    expect(productPanels).toContain('data-home-empty-products="true"');
  });

  it('keeps order tracking helpers and panels modularized outside the page shell', () => {
    const page = fs.readFileSync(path.join(__dirname, '..', 'pages', 'OrderTracking.tsx'), 'utf8');
    const helpers = fs.readFileSync(path.join(__dirname, '..', 'pages', 'orderTrackingHelpers.ts'), 'utf8');
    const panels = fs.readFileSync(path.join(__dirname, '..', 'pages', 'orderTrackingPanels.tsx'), 'utf8');
    expect(page).toContain("from './orderTrackingHelpers'");
    expect(page).toContain("from './orderTrackingPanels'");
    expect(page).toContain('<OrderTrackingMainPanels');
    expect(page).toContain('<OrderTrackingDialogs');
    expect(page).not.toContain('export const ORDER_TRACKING_AUTO_REFRESH_MS = 30_000');
    expect(page).not.toContain('const getTrackingStep =');
    expect(page).not.toContain('order-tracking-page__lookupCard');
    expect(page).not.toContain('order-tracking-page__returnModal');
    expect(helpers).toContain('export const ORDER_TRACKING_AUTO_REFRESH_MS');
    expect(helpers).toContain('export const shouldAutoRefreshTrackedOrder');
    expect(helpers).toContain('export const getTrackingStep');
    expect(helpers).toContain('export const resolveOrderTrackingNextActionDescriptor');
    expect(helpers).toContain('export const resolveOrderTrackingAssurancePlanDescriptor');
    expect(helpers).toContain('export const buildOrderTrackingActionLabels');
    expect(helpers).toContain('export const resolveOrderTrackingAccessFlags');
    expect(helpers).toContain('export const formatOrderTrackingStatusLabel');
    expect(helpers).toContain('export const resolveOrderTrackingStatusColor');
    expect(helpers).toContain('export const buildOrderTrackingPanelProps');
    expect(page).toContain('resolveOrderTrackingNextActionDescriptor({');
    expect(page).toContain('resolveOrderTrackingAssurancePlanDescriptor({');
    expect(page).toContain('buildOrderTrackingActionLabels({');
    expect(page).toContain('resolveOrderTrackingAccessFlags({');
    expect(page).toContain('buildOrderTrackingPanelProps({');
    expect(page).not.toContain('const nextAction = useMemo(() => {');
    expect(page).not.toContain('const canUseGuestActions = Boolean(isGuestTrackedOrder');
    expect(panels).toContain('export const OrderTrackingMainPanels');
    expect(panels).toContain('export const OrderTrackingDialogs');
    expect(panels).toContain('order-tracking-page__lookupCard');
    expect(panels).toContain('order-tracking-page__returnModal');
  });

  it('keeps wishlist helpers and panels modularized outside the page shell', () => {
    const page = fs.readFileSync(path.join(__dirname, '..', 'pages', 'Wishlist.tsx'), 'utf8');
    const helpers = fs.readFileSync(path.join(__dirname, '..', 'pages', 'wishlistHelpers.ts'), 'utf8');
    const panels = fs.readFileSync(path.join(__dirname, '..', 'pages', 'wishlistPanels.tsx'), 'utf8');
    expect(page).toContain("from './wishlistHelpers'");
    expect(page).toContain("from './wishlistPanels'");
    expect(page).toContain('<WishlistMainPanels');
    expect(page).toContain('<WishlistAuthGate');
    expect(page).toContain('<WishlistLoadingShell');
    expect(page).toContain('<WishlistEmptyShell');
    expect(page).toContain('<WishlistLoadErrorShell');
    expect(page).not.toContain('wishlist-page__grid');
    expect(page).not.toContain('wishlist-page__bestPick');
    expect(page).not.toContain('wishlist-page__authGate');
    expect(helpers).toContain('export const isPurchasable');
    expect(helpers).toContain('export const groupWishlistItems');
    expect(helpers).toContain('export const pickFeaturedWishlistItem');
    expect(helpers).toContain('export const WISHLIST_LOGIN_REQUIRED_MESSAGE_KEY');
    expect(helpers).toContain('export const buildWishlistActionLabels');
    expect(helpers).toContain('export const buildWishlistPanelProps');
    expect(helpers).toContain('export const buildWishlistRecoveryText');
    expect(helpers).toContain('export const resolveWishlistRecoveryActionDescriptor');
    expect(helpers).toContain('export const resolveWishlistNextActionDescriptor');
    expect(page).toContain('buildWishlistActionLabels({');
    expect(page).toContain('buildWishlistPanelProps({');
    expect(page).toContain('resolveWishlistNextActionDescriptor({');
    expect(page).not.toContain('const addAllToCartActionLabel =');
    expect(page).not.toContain('const recoveryText = directAddItems.length > 0');
    expect(panels).toContain('export const WishlistMainPanels');
    expect(panels).toContain('export const WishlistAuthGate');
    expect(panels).toContain('export const WishlistLoadingShell');
    expect(panels).toContain('export const WishlistEmptyShell');
    expect(panels).toContain('export const WishlistLoadErrorShell');
    expect(panels).toContain('wishlist-page__grid');
    expect(panels).toContain('wishlist-page__bestPick');
    expect(panels).toContain('wishlist-page__authGate');
    expect(panels).toContain('data-wishlist-load-recovery');
  });

  it('keeps login helpers and panels modularized outside the page shell', () => {
    const page = fs.readFileSync(path.join(__dirname, '..', 'pages', 'Login.tsx'), 'utf8');
    const helpers = fs.readFileSync(path.join(__dirname, '..', 'pages', 'loginHelpers.ts'), 'utf8');
    const panels = fs.readFileSync(path.join(__dirname, '..', 'pages', 'loginPanels.tsx'), 'utf8');
    expect(page).toContain("from './loginHelpers'");
    expect(page).toContain("from './loginPanels'");
    expect(page).toContain('<LoginMainPanels');
    expect(page).not.toContain('shopee-login-tabs__nav');
    expect(page).not.toContain('data-login-recovery-actions');
    expect(page).not.toContain('shopee-login-panel__title');
    expect(helpers).toContain('export const resolvePasswordLoginError');
    expect(helpers).toContain('export const normalizePasswordLogin');
    expect(helpers).toContain('export const shouldTryNextLoginCandidate');
    expect(helpers).toContain('export type LoginSessionResponse');
    expect(helpers).toContain('export const buildLoginActionLabels');
    expect(helpers).toContain('export const buildLoginPanelProps');
    expect(page).toContain('buildLoginActionLabels({');
    expect(page).toContain('buildLoginPanelProps({');
    expect(page).not.toContain("const loginPageLabel = t('pages.auth.loginTitle')");
    expect(page).not.toContain('const loginRegisterActionLabel =');
    expect(panels).toContain('export const LoginMainPanels');
    expect(panels).toContain('shopee-login-tabs__nav');
    expect(panels).toContain('data-login-recovery-actions');
    expect(panels).toContain('role="tablist"');
    expect(panels).toContain('shopee-login-panel__title');
  });


  it('keeps register helpers and panels modularized outside the page shell', () => {
    const page = fs.readFileSync(path.join(__dirname, '..', 'pages', 'Register.tsx'), 'utf8');
    const helpers = fs.readFileSync(path.join(__dirname, '..', 'pages', 'registerHelpers.ts'), 'utf8');
    const panels = fs.readFileSync(path.join(__dirname, '..', 'pages', 'registerPanels.tsx'), 'utf8');
    expect(page).toContain("from './registerHelpers'");
    expect(page).toContain("from './registerPanels'");
    expect(page).toContain('<RegisterMainPanels');
    expect(page).toContain('buildRegisterActionLabels({');
    expect(page).toContain('buildRegisterPanelProps({');
    expect(page).not.toContain('const registerLoginActionLabel =');
    expect(page).not.toContain('register-page__heroTitle');
    expect(helpers).toContain('export const buildRegisterActionLabels');
    expect(helpers).toContain('export const buildRegisterPanelProps');
    expect(helpers).toContain('export const resolveRegisterRecoveryKind');
    expect(helpers).toContain('export const scrollFirstRegisterErrorIntoView');
    expect(helpers).toContain('export const normalizeUsername');
    expect(panels).toContain('export const RegisterMainPanels');
    expect(panels).toContain('register-page__heroTitle');
    expect(panels).toContain('data-register-error-recovery');
    expect(panels).toContain('data-register-recovery-actions');
    expect(panels).toContain('register-page__legalNotice');
  });

  it('keeps forgot-password helpers and panels modularized outside the page shell', () => {
    const page = fs.readFileSync(path.join(__dirname, '..', 'pages', 'ForgotPassword.tsx'), 'utf8');
    const helpers = fs.readFileSync(path.join(__dirname, '..', 'pages', 'forgotPasswordHelpers.ts'), 'utf8');
    const panels = fs.readFileSync(path.join(__dirname, '..', 'pages', 'forgotPasswordPanels.tsx'), 'utf8');
    expect(page).toContain("from './forgotPasswordHelpers'");
    expect(page).toContain("from './forgotPasswordPanels'");
    expect(page).toContain('<ForgotPasswordMainPanels');
    expect(page).toContain('buildForgotPasswordActionLabels({');
    expect(page).toContain('buildForgotPasswordPanelProps({');
    expect(page).not.toContain('const resetPageLabel =');
    expect(page).not.toContain('shopee-login-subtitle--h1');
    expect(helpers).toContain('export const buildForgotPasswordActionLabels');
    expect(helpers).toContain('export const buildForgotPasswordPanelProps');
    expect(helpers).toContain('export const scrollFirstForgotPasswordErrorIntoView');
    expect(helpers).toContain('export const normalizePasswordLogin');
    expect(panels).toContain('export const ForgotPasswordMainPanels');
    expect(panels).toContain('shopee-login-subtitle--h1');
    expect(panels).toContain('data-forgot-password-unavailable');
    expect(panels).toContain('data-forgot-password-unavailable-actions');
  });

  it('keeps notifications helpers and panels modularized outside the page shell', () => {
    const page = fs.readFileSync(path.join(__dirname, '..', 'pages', 'Notifications.tsx'), 'utf8');
    const helpers = fs.readFileSync(path.join(__dirname, '..', 'pages', 'notificationsHelpers.ts'), 'utf8');
    const panels = fs.readFileSync(path.join(__dirname, '..', 'pages', 'notificationsPanels.tsx'), 'utf8');
    expect(page).toContain("from './notificationsHelpers'");
    expect(page).toContain("from './notificationsPanels'");
    expect(page).toContain('<NotificationsMainPanels');
    expect(page).toContain('<NotificationsAuthGateShell');
    expect(page).toContain('<NotificationsLoadingShell');
    expect(page).toContain('buildNotificationsActionLabels({');
    expect(page).toContain('buildNotificationsPanelProps({');
    expect(page).toContain('resolveNotificationActionPlanDescriptor({');
    expect(page).toContain('resolveNotificationRelatedPath(item)');
    expect(page).toContain('const openRelatedNotification = useCallback');
    expect(page).not.toContain('className="notifications-page__actionPlan"');
    expect(page).not.toContain('notifications-page__itemList');
    expect(helpers).toContain('export const NOTIFICATION_PAGE_SIZE = 50');
    expect(helpers).toContain('export const extractOrderNoFromNotification');
    expect(helpers).toContain('export const notificationLooksLikeShipment');
    expect(helpers).toContain('export const notificationLooksLikeReturnFlow');
    expect(helpers).toContain('export const deriveNotificationInsights');
    expect(helpers).toContain('export const filterNotificationsByQuickFilter');
    expect(helpers).toContain('export const resolveNotificationRelatedPath');
    expect(helpers).toContain('export const resolveNotificationActionPlanDescriptor');
    expect(helpers).toContain('export const buildNotificationsActionLabels');
    expect(helpers).toContain('export const buildNotificationsPanelProps');
    expect(helpers).toContain('`/track-order?orderNo=${encodeURIComponent(orderNo)}`');
    expect(panels).toContain('export const NotificationsMainPanels');
    expect(panels).toContain('export const NotificationsAuthGateShell');
    expect(panels).toContain('export const NotificationsLoadingShell');
    expect(panels).toContain('className="notifications-page__actionPlan"');
    expect(panels).toContain('notifications-page__itemList');
    expect(panels).toContain('data-notifications-load-recovery');
    expect(panels).toContain('data-notifications-filter-empty');
  });
  it('keeps browsing history helpers and panels modularized outside the page shell', () => {
    const page = fs.readFileSync(path.join(__dirname, '..', 'pages', 'BrowsingHistory.tsx'), 'utf8');
    const helpers = fs.readFileSync(path.join(__dirname, '..', 'pages', 'browsingHistoryHelpers.ts'), 'utf8');
    const panels = fs.readFileSync(path.join(__dirname, '..', 'pages', 'browsingHistoryPanels.tsx'), 'utf8');
    expect(page).toContain("from './browsingHistoryHelpers'");
    expect(page).toContain("from './browsingHistoryPanels'");
    expect(page).toContain('<BrowsingHistoryMainPanels');
    expect(page).toContain('<BrowsingHistoryLoadingShell');
    expect(page).toContain('buildBrowsingHistoryActionLabels({');
    expect(page).toContain('buildBrowsingHistoryPanelProps({');
    expect(page).toContain('resolveHistoryNextActionDescriptor({');
    expect(page).not.toContain('browsing-history__mobileAction');
    expect(page).not.toContain('data-history-load-recovery');
    expect(helpers).toContain('export const resolveHistoryNextActionDescriptor');
    expect(helpers).toContain('export const deriveHistoryInsights');
    expect(helpers).toContain('export const filterHistoryProducts');
    expect(helpers).toContain('export const buildBrowsingHistoryActionLabels');
    expect(helpers).toContain('export const buildBrowsingHistoryPanelProps');
    expect(helpers).toContain("title: t('pages.browsingHistory.nextActionStaleTitle')");
    expect(panels).toContain('export const BrowsingHistoryMainPanels');
    expect(panels).toContain('export const BrowsingHistoryLoadingShell');
    expect(panels).toContain('browsing-history__mobileAction');
    expect(panels).toContain('data-history-load-recovery');
    expect(panels).toContain('data-history-empty-actions');
  });
  it('keeps stock alerts helpers and panels modularized outside the page shell', () => {
    const page = fs.readFileSync(path.join(__dirname, '..', 'pages', 'StockAlerts.tsx'), 'utf8');
    const helpers = fs.readFileSync(path.join(__dirname, '..', 'pages', 'stockAlertsHelpers.ts'), 'utf8');
    const panels = fs.readFileSync(path.join(__dirname, '..', 'pages', 'stockAlertsPanels.tsx'), 'utf8');
    expect(page).toContain("from './stockAlertsHelpers'");
    expect(page).toContain("from './stockAlertsPanels'");
    expect(page).toContain('<StockAlertsMainPanels');
    expect(page).toContain('buildStockAlertsActionLabels({');
    expect(page).toContain('buildStockAlertsPanelProps({');
    expect(page).toContain('resolveStockAlertNextActionDescriptor({');
    expect(page).not.toContain('stock-alerts__mobileAction');
    expect(page).not.toContain('data-stock-alerts-load-recovery');
    expect(helpers).toContain('export const resolveStockAlertNextActionDescriptor');
    expect(helpers).toContain('export const deriveStockAlertInsights');
    expect(helpers).toContain('export const maskStaleStockAlertInsights');
    expect(helpers).toContain('export const buildStockAlertsActionLabels');
    expect(helpers).toContain('export const buildStockAlertsPanelProps');
    expect(helpers).toContain("title: t('pages.stockAlerts.nextActionStaleTitle')");
    expect(panels).toContain('export const StockAlertsMainPanels');
    expect(panels).toContain('stock-alerts__mobileAction');
    expect(panels).toContain('data-stock-alerts-load-recovery');
    expect(panels).toContain('data-stock-alerts-empty-actions');
  });




  it('keeps product compare helpers and panels modularized outside the page shell', () => {
    const page = fs.readFileSync(path.join(__dirname, '..', 'pages', 'ProductCompare.tsx'), 'utf8');
    const helpers = fs.readFileSync(path.join(__dirname, '..', 'pages', 'productCompareHelpers.ts'), 'utf8');
    const panels = fs.readFileSync(path.join(__dirname, '..', 'pages', 'productComparePanels.tsx'), 'utf8');
    expect(page).toContain("from './productCompareHelpers'");
    expect(page).toContain("from './productComparePanels'");
    expect(page).toContain('<ProductCompareMainPanels');
    expect(page).not.toContain('product-compare__decisionGrid');
    expect(page).not.toContain('data-compare-empty-actions');
    expect(page).not.toContain('data-compare-load-recovery');
    expect(helpers).toContain('export const buildCompareDecision');
    expect(helpers).toContain('export const getPrice');
    expect(helpers).toContain('export const collectCompareSpecKeys');
    expect(panels).toContain('export const ProductCompareMainPanels');
    expect(panels).toContain('product-compare__decisionGrid');
    expect(panels).toContain('data-compare-empty-actions');
    expect(panels).toContain('data-compare-load-recovery');
    expect(panels).toContain('data-compare-stale-recovery');
  });

  it('keeps coupon center helpers, shell, and panels modularized outside the page shell', () => {
    const page = fs.readFileSync(path.join(__dirname, '..', 'pages', 'CouponCenter.tsx'), 'utf8');
    const helpers = fs.readFileSync(path.join(__dirname, '..', 'pages', 'couponCenterPageHelpers.ts'), 'utf8');
    const shells = fs.readFileSync(path.join(__dirname, '..', 'pages', 'couponCenterShellStates.tsx'), 'utf8');
    const panels = fs.readFileSync(path.join(__dirname, '..', 'pages', 'couponCenterPanels.tsx'), 'utf8');
    expect(page).toContain("from './couponCenterPageHelpers'");
    expect(page).toContain("from './couponCenterShellStates'");
    expect(page).toContain("from './couponCenterPanels'");
    expect(page).toContain('<CouponCenterLoadingShell');
    expect(page).toContain('<CouponCenterConversionPanels');
    expect(page).toContain('<CouponCenterOpportunityPanels');
    expect(page).toContain('<CouponCenterClaimPanel');
    expect(page).toContain('<CouponCenterWalletPanel');
    expect(page).not.toContain('const CLAIM_BATCH_SIZE = 4');
    expect(page).not.toContain('const getCouponDisplayName =');
    expect(page).not.toContain('coupon-center-page--loading');
    expect(page).not.toContain('className={`coupon-center-page__hero');
    expect(page).not.toContain('id="coupon-claim-list"');
    expect(page).not.toContain('id="coupon-wallet"');
    expect(helpers).toContain('export const CLAIM_BATCH_SIZE');
    expect(helpers).toContain('export const claimCouponsInBatches');
    expect(helpers).toContain('export const getCouponDisplayName');
    expect(shells).toContain('export const CouponCenterLoadingShell');
    expect(shells).toContain('data-coupon-loading-shell="true"');
    expect(panels).toContain('export const CouponCenterConversionPanels');
    expect(panels).toContain('export const CouponCenterClaimPanel');
    expect(panels).toContain('export const CouponCenterWalletPanel');
    expect(panels).toContain('coupon-center-page__hero');
    expect(panels).toContain('id="coupon-claim-list"');
    expect(panels).toContain('id="coupon-wallet"');
  });

  it('keeps payment instructions panels and sticky rails modularized outside the page shell', () => {
    const page = fs.readFileSync(path.join(__dirname, '..', 'pages', 'PaymentInstructions.tsx'), 'utf8');
    const panels = fs.readFileSync(path.join(__dirname, '..', 'pages', 'paymentInstructionsPanels.tsx'), 'utf8');
    const sticky = fs.readFileSync(path.join(__dirname, '..', 'pages', 'paymentInstructionsStickyBars.tsx'), 'utf8');

    expect(page).toContain("from './paymentInstructionsPanels'");
    expect(page).toContain("from './paymentInstructionsStickyBars'");
    expect(page).toContain('<PaymentInstructionsPanels');
    expect(page).toContain('<PaymentInstructionsStickyBars');
    expect(page).not.toContain('className="payment-instructions-page__hero"');
    expect(page).not.toContain('className="payment-instructions-page__descList"');
    expect(page).not.toContain('className="payment-instructions-page__stickyBar"');
    expect(page).not.toContain('data-payment-guest-email-gate="true"');
    expect(panels).toContain('export const PaymentInstructionsPanels');
    expect(panels).toContain('payment-instructions-page__hero');
    expect(panels).toContain('payment-instructions-page__descList');
    expect(panels).toContain('data-payment-guest-email-gate="true"');
    expect(panels).toContain('payment-instructions-page__trustBar');
    expect(sticky).toContain('export const PaymentInstructionsStickyBars');
    expect(sticky).toContain('payment-instructions-page__stickyBar');
    expect(sticky).toContain('data-payment-recovery-sticky="true"');
    expect(sticky).toContain('data-payment-paid-sticky="true"');
  });

  it('keeps profile payment, address, and pet actions modularized outside the page shell', () => {
    const page = fs.readFileSync(path.join(__dirname, '..', 'pages', 'Profile.tsx'), 'utf8');
    const helpers = fs.readFileSync(path.join(__dirname, 'profileHelpers.ts'), 'utf8');
    const payment = fs.readFileSync(path.join(__dirname, '..', 'hooks', 'useProfilePaymentActions.ts'), 'utf8');
    const address = fs.readFileSync(path.join(__dirname, '..', 'hooks', 'useProfileAddressActions.ts'), 'utf8');
    const pet = fs.readFileSync(path.join(__dirname, '..', 'hooks', 'useProfilePetActions.ts'), 'utf8');
    const ordersPanel = fs.readFileSync(path.join(__dirname, '..', 'pages', 'profileOrdersPanel.tsx'), 'utf8');
    const addressesPanel = fs.readFileSync(path.join(__dirname, '..', 'pages', 'profileAddressesPanel.tsx'), 'utf8');
    const petsPanel = fs.readFileSync(path.join(__dirname, '..', 'pages', 'profilePetsPanel.tsx'), 'utf8');
    const orderDetailModal = fs.readFileSync(path.join(__dirname, '..', 'pages', 'profileOrderDetailModal.tsx'), 'utf8');
    const returnModals = fs.readFileSync(path.join(__dirname, '..', 'pages', 'profileReturnModals.tsx'), 'utf8');
    const paymentModal = fs.readFileSync(path.join(__dirname, '..', 'pages', 'profilePaymentModal.tsx'), 'utf8');
    const infoPanel = fs.readFileSync(path.join(__dirname, '..', 'pages', 'profileInfoPanel.tsx'), 'utf8');
    const accountModals = fs.readFileSync(path.join(__dirname, '..', 'pages', 'profileAccountModals.tsx'), 'utf8');
    const shell = fs.readFileSync(path.join(__dirname, '..', 'pages', 'profileShellPanels.tsx'), 'utf8');
    const account = fs.readFileSync(path.join(__dirname, '..', 'hooks', 'useProfileAccountActions.ts'), 'utf8');
    const order = fs.readFileSync(path.join(__dirname, '..', 'hooks', 'useProfileOrderActions.ts'), 'utf8');
    const session = fs.readFileSync(path.join(__dirname, '..', 'hooks', 'useProfileSessionData.ts'), 'utf8');
    const paymentReturn = fs.readFileSync(path.join(__dirname, '..', 'hooks', 'useProfilePaymentReturn.ts'), 'utf8');

    expect(page).toContain("from '../utils/profileHelpers'");
    expect(page).toContain("from './profileShellPanels'");
    expect(page).toContain('<ProfileAuthGateShell');
    expect(page).toContain('<ProfileLoadingShell');
    expect(page).toContain('<ProfileMainShell');
    expect(shell).toContain('export const ProfileMainShell');
    expect(shell).toContain('profile-overview');
    expect(shell).toContain('profile-action-center');
    expect(page).not.toContain('profile-overview');
    expect(page).not.toContain('data-auth-gate="profile-login-required"');
    expect(page).not.toContain('className="profile-loading"');
    expect(page).toContain("from '../hooks/useProfilePaymentActions'");
    expect(page).toContain("from '../hooks/useProfileAddressActions'");
    expect(page).toContain("from '../hooks/useProfilePetActions'");
    expect(shell).toContain("from './profileOrdersPanel'");
    expect(page).toContain("from '../hooks/useProfileAccountActions'");
    expect(page).toContain("from '../hooks/useProfileOrderActions'");
    expect(page).toContain("from '../hooks/useProfileSessionData'");
    expect(page).toContain("from '../hooks/useProfilePaymentReturn'");
    expect(page).toContain('useProfilePaymentActions({');
    expect(page).toContain('useProfileAddressActions({');
    expect(page).toContain('useProfilePetActions({');
    expect(shell).toContain('<ProfileOrdersPanel');
    expect(page).toContain('useProfileAccountActions({');
    expect(page).toContain('useProfileOrderActions({');
    expect(page).toContain('useProfileSessionData({');
    expect(page).toContain('useProfilePaymentReturn({');
    expect(page).not.toContain('const fetchUserInfo = useCallback');
    expect(page).not.toContain('const fetchOrders = useCallback');
    expect(page).not.toContain('const fetchAddresses = useCallback');
    expect(page).not.toContain('const fetchPetProfiles = useCallback');
    expect(page).not.toContain('const syncPaymentReturnState = useCallback');
    expect(helpers).toContain('export const normalizeProfileTab');
    expect(helpers).toContain('export const isCompleteProfileAddress');
    expect(helpers).toContain('export const deriveProfileDashboardMetrics');
    expect(helpers).toContain('export const filterProfileOrders');
    expect(helpers).toContain('export const getOrderActionHint');
    expect(helpers).toContain('export const buildProfileAfterSaleFocusText');
    expect(helpers).toContain('export const buildProfileActionLabels');
    expect(helpers).toContain('export const buildProfileMainShellProps');
    expect(page).toContain('buildProfileActionLabels({');
    expect(page).toContain('buildProfileMainShellProps({');
    expect(page).not.toContain('const editProfileActionLabel =');
    expect(page).not.toContain('const selectedOrderTrackActionLabel = selectedOrder');
    expect(page).toContain('deriveProfileDashboardMetrics({');
    expect(page).toContain('filterProfileOrders({');
    expect(page).toContain('getOrderActionHintHelper({');
    expect(payment).toContain('export const useProfilePaymentActions');
    expect(address).toContain('export const useProfileAddressActions');
    expect(address).toContain('const handleSaveAddress = async () => {');
    expect(pet).toContain('export const useProfilePetActions');
    expect(pet).toContain('const handleSavePet = async () => {');
    expect(ordersPanel).toContain('export const ProfileOrdersPanel');
    expect(addressesPanel).toContain('export const ProfileAddressesPanel');
    expect(petsPanel).toContain('export const ProfilePetsPanel');
    expect(shell).toContain("from './profileAddressesPanel'");
    expect(shell).toContain("from './profilePetsPanel'");
    expect(shell).toContain('<ProfileAddressesPanel');
    expect(shell).toContain('<ProfilePetsPanel');
    expect(petsPanel).toContain('handleDeletePet(pet.id)');
    expect(orderDetailModal).toContain('export const ProfileOrderDetailModal');
    expect(returnModals).toContain('export const ProfileReturnModals');
    expect(paymentModal).toContain('export const ProfilePaymentModal');
    expect(shell).toContain("from './profileOrderDetailModal'");
    expect(shell).toContain("from './profileReturnModals'");
    expect(shell).toContain("from './profilePaymentModal'");
    expect(shell).toContain('<ProfileOrderDetailModal');
    expect(shell).toContain('<ProfileReturnModals');
    expect(shell).toContain('<ProfilePaymentModal');
    expect(paymentModal).toContain('data-profile-payment-history-empty="true"');
    expect(infoPanel).toContain('export const ProfileInfoPanel');
    expect(accountModals).toContain('export const ProfileAccountModals');
    expect(shell).toContain("from './profileInfoPanel'");
    expect(shell).toContain("from './profileAccountModals'");
    expect(shell).toContain('<ProfileInfoPanel');
    expect(shell).toContain('<ProfileAccountModals');
    expect(ordersPanel).toContain('data-profile-orders-load-recovery="true"');
    expect(ordersPanel).toContain('className="profile-order-card"');
    expect(page).not.toContain('data-profile-orders-load-recovery="true"');
    expect(account).toContain('export const useProfileAccountActions');
    expect(account).toContain('const handleEditProfile = async () => {');
    expect(order).toContain('export const useProfileOrderActions');
    expect(order).toContain('const handleViewOrder = async (order: OrderCustomer) => {');
    expect(page).not.toContain('const handleSaveAddress = async () => {');
    expect(page).not.toContain('const openPetModal = (pet?: PetProfile) => {');
    expect(page).not.toContain('const handleEditProfile = async () => {');
    expect(page).not.toContain('const handleViewOrder = async (order: OrderCustomer) => {');
    expect(session).toContain('export const useProfileSessionData');
    expect(session).toContain('const fetchOrders = useCallback');
    expect(session).toContain('const fetchPetProfiles = useCallback');
    expect(paymentReturn).toContain('export const useProfilePaymentReturn');
    expect(paymentReturn).toContain('const syncPaymentReturnState = useCallback');
  });


  it('keeps local UI server proxying API to the backend origin', () => {
    const serve = readFrontendRoot('scripts', 'serve-build.js');
    expect(serve).toContain('SHOPTEST_BACKEND_ORIGIN');
    expect(serve).toContain('/api');
    expect(serve).toMatch(/8081|BACKEND_ORIGIN|backendOrigin/);
  });

  it('keeps commercial security and static cache headers on the local UI server', () => {
    const serve = readFrontendRoot('scripts', 'serve-build.js');
    const smoke = readFrontendRoot('scripts', 'commercial-http-smoke.js');
    expect(serve).toContain('commercialSecurityHeaders');
    expect(serve).toContain('X-Content-Type-Options');
    expect(serve).toContain('X-Frame-Options');
    expect(serve).toContain('Referrer-Policy');
    expect(serve).toContain('Content-Security-Policy');
    expect(serve).toContain('max-age=31536000, immutable');
    expect(serve).toContain("rel.startsWith('static/')");
    expect(smoke).toContain('ui security headers');
    expect(smoke).toContain('static js long-cache immutable');
  });

  it('keeps a Playwright commercial browser smoke entry for rendered storefront gates', () => {
    const pkg = JSON.parse(readFrontendRoot('package.json'));
    const browserSmoke = readFrontendRoot('scripts', 'commercial-browser-smoke.js');
    const httpSmoke = readFrontendRoot('scripts', 'commercial-http-smoke.js');
    expect(pkg.scripts['test:commercial-browser-smoke']).toContain('commercial-browser-smoke.js');
    expect(browserSmoke).toContain("require('playwright')");
    expect(browserSmoke).toContain('/cart');
    expect(browserSmoke).toContain('/checkout');
    expect(browserSmoke).toContain('/track-order');
    expect(browserSmoke).toContain('skip link present');
    expect(browserSmoke).toContain('no page errors');
    expect(browserSmoke).toContain('home main content');
    expect(browserSmoke).toContain('cart empty multi-path CTAs');
    expect(browserSmoke).toContain('products catalog populated');
    expect(browserSmoke).toContain('browser auth login success');
    expect(browserSmoke).toContain('browser auth register rate-limit handled');
    expect(browserSmoke).toContain('/api/auth/register');
    expect(browserSmoke).toContain('readMainText');
    expect(browserSmoke).toContain('home LCP soft budget');
    expect(browserSmoke).toContain('Warm home once so cold post-rebuild asset compile does not flake the LCP soft gate');
    expect(browserSmoke).toContain('built multipath recovery markers present');
    expect(browserSmoke).toContain('home CLS soft budget');
    expect(browserSmoke).toContain('cwv.cls < 0.1');
    expect(browserSmoke).toContain('home mobile bottom bar height locked');
    expect(browserSmoke).toContain('cwv.lcp < 4000');
    expect(browserSmoke).toContain('product-mobile-buybar');
    expect(browserSmoke).toContain('login legal agreement notice');
    expect(browserSmoke).toContain('wishlist guest multi-path auth gate');
    expect(browserSmoke).toContain('notifications guest multi-path auth gate');
    expect(browserSmoke).toContain('profile guest multi-path auth gate');
    expect(browserSmoke).toContain('compare empty multi-path CTAs');
    expect(browserSmoke).toContain('product detail bottom nav hidden for buybar');
    expect(browserSmoke).toContain('__shopmxCwv');
    expect(browserSmoke).toContain('PerformanceObserver');
    expect(httpSmoke).toContain('robots.txt allows privacy');
    expect(httpSmoke).toContain('robots.txt allows products detail');
    expect(httpSmoke).toContain('security.txt');
    expect(httpSmoke).toContain('sitemap.xml includes terms');
    expect(httpSmoke).toContain('sitemap.xml includes product detail');
    expect(browserSmoke).toContain('/forgot-password');
    expect(browserSmoke).toContain('/privacy');
    expect(browserSmoke).toContain('cookie consent banner');
    expect(browserSmoke).toContain('cookie consent sticky rail selectors');
    expect(browserSmoke).toContain('customer-support-widget__button');
    expect(browserSmoke).toContain('product-list__mobileConversionBar');
    expect(browserSmoke).toContain('data-checkout-recovery-path');
    expect(browserSmoke).toContain('checkoutRecoveryPaths.length >= 4');
    expect(browserSmoke).toContain("!clearanceCss.includes('shop-nav__bottomBar')");
    expect(browserSmoke).toContain('/terms');
    expect(browserSmoke).toContain('/wishlist');
    expect(browserSmoke).toContain('/history');
    // Fixed smoke credentials avoid register thrash; login selectors must not match language Select.
    expect(browserSmoke).toContain('SHOPTEST_SMOKE_AUTH_USER');
    expect(browserSmoke).toContain('SHOPTEST_SMOKE_AUTH_PASSWORD');
    expect(browserSmoke).toContain('form.shopee-login-form input[autocomplete="username"]');
    expect(browserSmoke).toContain("localStorage.getItem('token')");
    expect(browserSmoke).toContain('([1-9]\\d*)\\s+products?');
    expect(httpSmoke).toContain('SHOPTEST_SMOKE_AUTH_USER');
    expect(httpSmoke).toContain('PAYMENT_CALLBACK_SECRET');
  });

  it('keeps Mercado Pago webhook endpoint wired for MX production paid recovery', () => {
    const paymentController = fs.readFileSync(path.join(__dirname, '..', '..', '..', 'src/main/java/com/example/shop/controller/PaymentController.java'), 'utf8');
    const paymentService = fs.readFileSync(path.join(__dirname, '..', '..', '..', 'src/main/java/com/example/shop/service/PaymentService.java'), 'utf8');
    const security = fs.readFileSync(path.join(__dirname, '..', '..', '..', 'src/main/java/com/example/shop/config/SecurityConfig.java'), 'utf8');
    const smoke = readFrontendRoot('scripts', 'commercial-http-smoke.js');
    expect(paymentController).toContain('/mercado-pago/webhook');
    expect(paymentController).toContain('handleMercadoPagoWebhook');
    expect(paymentService).toContain('verifyMercadoPagoSignature');
    expect(paymentService).toContain('fetchMercadoPagoPayment');
    expect(paymentService).toContain('id:');
    expect(paymentService).toContain('request-id:');
    expect(security).toContain('/payments/mercado-pago/webhook');
    expect(smoke).toContain("id:${dataId};request-id:${requestId};ts:${ts};");
  });

  it('keeps admin system status payment webhook readiness surface for ops', () => {
    const adminSystem = fs.readFileSync(path.join(__dirname, '..', '..', '..', 'src/main/java/com/example/shop/controller/AdminSystemController.java'), 'utf8');
    const systemMonitor = fs.readFileSync(path.join(__dirname, '..', 'pages', 'SystemMonitor.tsx'), 'utf8');
    expect(adminSystem).toContain('adminOperationalStatusPayload');
    expect(adminSystem).toContain('enrichPaymentProviderWebhookReadiness');
    expect(adminSystem).toContain('webhookReadyChannelCount');
    expect(adminSystem).toContain('payment.mercado-pago.webhook-secret');
    expect(adminSystem).toContain('stripe.webhook-secret');
    expect(systemMonitor).toContain('paymentWebhooks');
    expect(systemMonitor).toContain('channelWebhookReady');
    expect(systemMonitor).toContain('webhookReadyChannelCount');
    expect(systemMonitor).toContain('data-webhook-status');
    expect(systemMonitor).toContain('data-system-monitor-load-recovery');
    expect(systemMonitor).toContain("navigate('/admin')");
    expect(systemMonitor).toContain("navigate('/admin/orders')");
    expect(systemMonitor).toContain('actions={[');
  });

  it('keeps admin dashboard drilldown into payment provider webhook readiness', () => {
    const dashboard = fs.readFileSync(path.join(__dirname, '..', 'pages', 'AdminDashboard.tsx'), 'utf8');
    const en = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'locales', 'en.json'), 'utf8'));
    expect(dashboard).toContain("navigate('/admin/system')");
    expect(dashboard).toContain('providerReadinessAction');
    expect(dashboard).toContain('data-admin-payment-provider-readiness');
    expect(en.pages.adminDashboard.paymentReturnOps.providerReadinessAction).toBeTruthy();
  });

  it('keeps admin dashboard load failures on multipath ops recovery exits', () => {
    const dashboard = fs.readFileSync(path.join(__dirname, '..', 'pages', 'AdminDashboard.tsx'), 'utf8');
    expect(dashboard).toContain('data-admin-dashboard-load-recovery');
    expect(dashboard).toContain('actions={[');
    expect(dashboard).toContain("navigate('/admin/orders')");
    expect(dashboard).toContain("navigate('/admin/system')");
    expect(dashboard).toContain("navigate('/admin/products')");
  });

  it('keeps commercial-critical admin load failures on multipath ops recovery exits', () => {
    const orders = fs.readFileSync(path.join(__dirname, '..', 'pages', 'OrderManagement.tsx'), 'utf8');
    const products = fs.readFileSync(path.join(__dirname, '..', 'pages', 'ProductManagement.tsx'), 'utf8');
    const coupons = fs.readFileSync(path.join(__dirname, '..', 'pages', 'CouponManagement.tsx'), 'utf8');
    const support = fs.readFileSync(path.join(__dirname, '..', 'pages', 'SupportManagement.tsx'), 'utf8');
    const system = fs.readFileSync(path.join(__dirname, '..', 'pages', 'SystemMonitor.tsx'), 'utf8');

    expect(orders).toContain('data-admin-orders-load-recovery');
    expect(orders).toContain('data-admin-orders-stale-recovery');
    expect(orders).toContain("navigate('/admin/system')");
    expect(orders).toContain("navigate('/admin/support')");
    expect(orders).toContain('actions={[');

    expect(products).toContain('data-admin-products-load-recovery');
    expect(products).toContain('data-admin-products-stale-recovery');
    expect(products).toContain("navigate('/admin/orders')");
    expect(products).toContain('actions={[');

    expect(coupons).toContain('data-admin-coupons-load-recovery');
    expect(coupons).toContain('data-admin-coupons-stale-recovery');
    expect(coupons).toContain("navigate('/admin/orders')");
    expect(coupons).toContain('actions={[');

    expect(support).toContain('data-admin-support-queue-recovery');
    expect(support).toContain('data-admin-support-messages-recovery');
    expect(support).toContain("navigate('/admin/orders')");
    expect(support).toContain("navigate('/admin/system')");

    expect(system).toContain('data-system-monitor-load-recovery');
    expect(system).toContain('data-system-monitor-stale-recovery');

    const users = fs.readFileSync(path.join(__dirname, '..', 'pages', 'UserManagement.tsx'), 'utf8');
    expect(users).toContain('data-admin-users-load-recovery');
    expect(users).toContain('data-admin-users-stale-recovery');
    expect(users).toContain("navigate('/admin/orders')");
    expect(users).toContain('actions={[');

    for (const [file, loadMarker, staleMarker] of [
      ['CategoryManagement.tsx', 'data-admin-categories-load-recovery', 'data-admin-categories-stale-recovery'],
      ['BrandManagement.tsx', 'data-admin-brands-load-recovery', 'data-admin-brands-stale-recovery'],
      ['LogisticsCarrierManagement.tsx', 'data-admin-carriers-load-recovery', 'data-admin-carriers-stale-recovery'],
      ['ReviewManagement.tsx', 'data-admin-reviews-load-recovery', 'data-admin-reviews-stale-recovery'],
      ['SecurityAuditLogManagement.tsx', 'data-admin-audit-load-recovery', 'data-admin-audit-stale-recovery'],
      ['AlertManagement.tsx', 'data-admin-alerts-load-recovery', 'data-admin-alerts-stale-recovery'],
      ['AnnouncementManagement.tsx', 'data-admin-announcements-load-recovery', 'data-admin-announcements-stale-recovery'],
      ['IpBlacklistManagement.tsx', 'data-admin-ip-blacklist-load-recovery', 'data-admin-ip-blacklist-stale-recovery'],
      ['ConfigCenter.tsx', 'data-admin-config-load-recovery', 'data-admin-config-stale-recovery'],
      ['LogManagement.tsx', 'data-admin-logs-load-recovery', 'data-admin-logs-stale-recovery'],
      ['PermissionManagement.tsx', 'data-admin-permissions-load-recovery', 'data-admin-permissions-stale-recovery'],
      ['PetGalleryManagement.tsx', 'data-admin-pet-gallery-load-recovery', 'data-admin-pet-gallery-stale-recovery'],
      ['ProductQuestionManagement.tsx', 'data-admin-questions-load-recovery', 'data-admin-questions-stale-recovery'],
      ['RegistryManagement.tsx', 'data-admin-registry-load-recovery', 'data-admin-registry-stale-recovery'],
      ['TrafficControl.tsx', 'data-admin-traffic-load-recovery', 'data-admin-traffic-stale-recovery'],
      ['BugManagement.tsx', 'data-admin-bugs-load-recovery', 'data-admin-bugs-stale-recovery'],
    ] as const) {
      const source = fs.readFileSync(path.join(__dirname, '..', 'pages', file), 'utf8');
      expect(source).toContain(loadMarker);
      expect(source).toContain(staleMarker);
      expect(source).toContain('actions={[');
      expect(source).toContain("navigate('/admin')");
    }
    const bugs = fs.readFileSync(path.join(__dirname, '..', 'pages', 'BugManagement.tsx'), 'utf8');
    expect(bugs).toContain('data-admin-bugs-summary-load-recovery');
    expect(bugs).toContain('data-admin-bugs-summary-stale-recovery');
  });

  it('keeps multi-host storefront payment URL rewrite contracts in commercial HTTP smoke', () => {
    const smoke = readFrontendRoot('scripts', 'commercial-http-smoke.js');
    expect(smoke).toContain('payment url storefront payment path');
    expect(smoke).toContain('payment url rewrites onto current UI origin');
    expect(smoke).toContain('payment instructions spa on current UI');
    expect(smoke).toContain('isStorefrontPaymentPath');
  });

  it('keeps an atomic commercial frontend build entry that avoids mid-build UI outages', () => {
    const pkg = JSON.parse(readFrontendRoot('package.json'));
    const safeBuild = readFrontendRoot('scripts', 'safe-commercial-build.sh');
    // Default `npm run build` must be atomic: staging build then swap into live build/.
    expect(pkg.scripts.build).toContain('safe-commercial-build.sh');
    expect(pkg.scripts['build:commercial']).toContain('safe-commercial-build.sh');
    expect(pkg.scripts['build:raw']).toContain('react-scripts build');
    expect(safeBuild).toContain('BUILD_PATH');
    expect(safeBuild).toContain('build.next');
    expect(safeBuild).toContain('inode-preserving');
    expect(safeBuild).toContain('DISABLE_ESLINT_PLUGIN');
    // Direct react-scripts call avoids recursive npm run build loops.
    expect(safeBuild).toContain('react-scripts build');
    expect(safeBuild).not.toMatch(/(^|\n)\s*npm run build\b/);
  });

});
